const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const serve=require('./server.cjs');
const engineState=async p=>p.evaluate(()=>{const key=Object.keys(localStorage).find(k=>k.endsWith(new URL(location).searchParams.get('mode')==='demo'?':module4:v1:demo':':module4:v1'));return key?JSON.parse(localStorage.getItem(key)):null;});
const passed=[];let browser,server;
async function check(name,fn){await fn();passed.push(name);console.log('PASS',name);}
(async()=>{
 const site=await serve();server=site.server;const base=site.base;
 browser=await chromium.launch({headless:true,executablePath:process.env.ASNM_BROWSER_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await context.route('https://fonts.googleapis.com/**',r=>r.fulfill({body:''}));
 if(process.env.ASNM_CHART_JS_PATH)await context.route('https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.0/chart.umd.min.js',r=>r.fulfill({path:process.env.ASNM_CHART_JS_PATH,contentType:'application/javascript'}));
 const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const out=process.env.ASNM_SCREENSHOT_DIR;
 if(out)await fs.mkdir(out,{recursive:true});
 await check('Korean/English landing, three entries, no Babylon on home',async()=>{
  for(const prefix of ['', '/en']){await p.goto(base+prefix+'/');await p.locator('#demo-start').waitFor();assert.equal(await p.locator('#page-home .p-entry-choice').count(),3);assert.equal(await p.locator('#page-questions .p-question-card').count(),4);assert.equal(await p.evaluate(()=>typeof BABYLON),'undefined');}
  await p.goto(base+'/');if(out)await p.screenshot({path:path.join(out,'v4-home-desktop.png'),fullPage:true});
 });
 await check('question routes select market/founder/digital-twin destinations',async()=>{
  await p.locator('#page-home .p-entry-choice').nth(1).click();await p.locator('#page-questions [data-module="m1"]').click();assert.equal(await p.locator('#page-m1').isVisible(),true);await p.evaluate(()=>showPage('questions'));await p.locator('#page-questions [data-module="m2"]').click();assert.equal(await p.locator('#page-m2').isVisible(),true);await p.evaluate(()=>showPage('questions'));await p.locator('#page-questions [data-module="m4"]').click();await p.locator('#setup-idea').fill('Pricing venture');await p.locator('#review-start').click();await p.locator('#enter-decision-world').click();await p.locator('[data-option]').first().waitFor();
 });
 await check('solo revenue setup stays valid and editing preserves role while applying stage/team/runway choices',async()=>{
  const ctx=await browser.newContext({viewport:{width:390,height:844}});const page=await ctx.newPage();await page.goto(base+'/module4/?lang=en');await page.locator('#setup-idea').fill('Solo revenue');await page.locator('#setup-stage').selectOption('revenue');await page.locator('#setup-role').selectOption('CFO');await page.locator('#setup-funds').selectOption('3-6');await page.locator('#review-start').click();assert.match(await page.locator('.p-metrics').innerText(),/4.5 mo/);await page.getByRole('button',{name:'Edit assumptions',exact:true}).click();assert.equal(await page.locator('#setup-role').inputValue(),'CFO');assert.equal(await page.locator('#setup-stage').inputValue(),'revenue');await page.locator('#setup-stage').selectOption('interview');await page.locator('#setup-team').selectOption('large');await page.locator('#setup-funds').selectOption('0-3');await page.locator('#review-start').click();await page.locator('#enter-decision-world').click();const state=await engineState(page);assert.equal(state.state.venture.productProgress,20);assert.equal(state.state.venture.teamSize,5);assert.equal(state.state.venture.runway,2);assert.equal(state.productRole,'CFO');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await ctx.close();
 });
 await check('automatic briefing and interrupted decision drafts survive navigation/refresh without committing a month',async()=>{
  const ctx=await browser.newContext({viewport:{width:1440,height:1000}});const page=await ctx.newPage(),issues=[];page.on('pageerror',e=>issues.push(e.message));await page.goto(base+'/module4/?mode=demo&lang=en&view=workspace');await page.locator('#morning-brief').waitFor();const state=await engineState(page);assert.equal(state.history.length,0);assert.equal(await page.locator('#morning-brief [data-brief-role]').count(),3);await page.waitForFunction(()=>document.querySelector('#agent-bubble strong').textContent==='Growth');assert.deepEqual(await engineState(page),state);await page.locator('[data-option="discover"]').click();await page.locator('#team-discussion').waitFor();await page.locator('#founder-context').fill('Hold hiring and interview five customers.');await page.locator('#expected-growth').fill('25');await page.locator('#view-report').click();await page.locator('#view-decision').click();assert.equal(await page.locator('#founder-context').inputValue(),'Hold hiring and interview five customers.');await page.reload();await page.locator('#team-discussion').waitFor();assert.equal(await page.locator('#expected-growth').inputValue(),'25');assert.equal(await page.locator('[data-option="discover"]').getAttribute('aria-pressed'),'true');assert.equal((await engineState(page)).history.length,0);await page.locator('#commit-decision').click();await page.locator('#decision-outcome').waitFor();const committed=await engineState(page);assert.equal(committed.history.length,1);assert.equal(committed.productDraft,undefined);assert.equal(committed.decisionJournal[0].expectedGrowth,25);assert.deepEqual(issues,[]);await ctx.close();
 });
 await check('rapid navigation during a delayed 3D download evaluates Babylon exactly once',async()=>{
  const ctx=await browser.newContext({viewport:{width:1280,height:900}});let release;const gate=new Promise(resolve=>release=resolve);await ctx.route('**/module4/vendor/babylon.js',async route=>{await gate;await route.continue();});const page=await ctx.newPage(),issues=[];page.on('pageerror',e=>issues.push(e.message));await page.goto(base+'/module4/?mode=demo&lang=en&view=workspace',{waitUntil:'domcontentloaded'});await page.locator('#view-report').waitFor();for(let i=0;i<3;i++){await page.locator('#view-report').click();await page.locator('#view-decision').click();}assert.equal(await page.locator('script[src="./vendor/babylon.js"]').count(),1);release();await page.waitForFunction(()=>document.querySelector('#living-world')?.dataset.ready==='true');await page.locator('[data-option]').last().click();await page.locator('#team-discussion').waitFor();await page.locator('#commit-decision').click();await page.locator('#decision-outcome').waitFor();assert.deepEqual(issues,[]);await ctx.close();
 });
 await check('three-minute demo: decision, six-role discussion, simulated outcome, three next actions',async()=>{
  await p.goto(base+'/module4/?mode=demo&lang=en&view=workspace');await p.waitForFunction(()=>document.querySelector('#living-world')?.dataset.ready==='true');await p.locator('[data-option="developer"]').click();await p.locator('#team-discussion').waitFor();assert.equal(await p.locator('.p-turn').count(),6);assert.match(await p.locator('#advisor-mode').innerText(),/Rule-based/);await p.locator('#founder-context').fill('Test our delivery assumption.');await p.locator('#expected-growth').fill('20');if(out)await p.screenshot({path:path.join(out,'v4-world-desktop.png'),fullPage:true});await p.locator('#commit-decision').click();await p.locator('#decision-outcome').waitFor();assert.equal(await p.locator('#decision-outcome ol li').count(),3);const state=await engineState(p);assert.equal(state.history.length,1);assert.equal(state.state.venture.teamSize,4);assert.equal(state.decisionJournal[0].expectedGrowth,20);
 });
 await check('refresh, role choice, movement, first/third camera and JSON export/import preserve reproducible state',async()=>{
  await p.locator('#player-role').selectOption('CFO');await p.reload();await p.waitForFunction(()=>document.querySelector('#living-world')?.dataset.ready==='true');assert.equal(await p.locator('#player-role').inputValue(),'CFO');const data=await engineState(p);assert.equal(data.history.length,1);await p.waitForFunction(()=>BABYLON.EngineStore.LastCreatedScene.getTransformNodeByName('founder').metadata.roomId==='finance');const pos=await p.evaluate(()=>BABYLON.EngineStore.LastCreatedScene.getTransformNodeByName('founder').position.z);await p.locator('#living-world').focus();await p.keyboard.press('w');await p.waitForTimeout(1000);assert.notEqual(await p.evaluate(()=>BABYLON.EngineStore.LastCreatedScene.getTransformNodeByName('founder').position.z),pos);await p.getByRole('button',{name:'First person',exact:true}).click();await p.waitForFunction(()=>BABYLON.EngineStore.LastCreatedScene.activeCamera.radius===.8);assert.equal(await p.evaluate(()=>BABYLON.EngineStore.LastCreatedScene.activeCamera.radius),.8);await p.getByRole('button',{name:'Third person',exact:true}).click();const pending=p.waitForEvent('download');await p.getByRole('button',{name:'Export',exact:true}).click();const d=await pending;const bytes=await fs.readFile(await d.path());assert.equal(JSON.parse(bytes).history.length,1);await p.locator('input[type=file]').setInputFiles({name:'session.json',mimeType:'application/json',buffer:bytes});await p.getByRole('dialog').getByRole('button',{name:'Start new',exact:true}).click();await p.locator('#decision-outcome').waitFor();assert.equal((await engineState(p)).history.length,1);
 });
 await check('counterfactual same seed; comparison never changes committed state',async()=>{
  const before=await engineState(p);await p.locator('#view-compare').click();await p.locator('#comparison-results table').waitFor();assert.equal(await p.locator('[data-compare]').count(),8);assert.match(await p.locator('caption').innerText(),/Same state/);await p.locator('#scenario-b').selectOption('discover');assert.deepEqual(await engineState(p),before);assert.notEqual(await p.locator('[data-compare="runway"] td').nth(0).innerText(),await p.locator('[data-compare="runway"] td').nth(1).innerText());
 });
 await check('journal reflection saves; ten-section action plan exports actual data',async()=>{
  await p.locator('#view-journal').click();await p.locator('textarea[data-reflection]').fill('Check paid conversion first.');await p.locator('textarea[data-reflection]').blur();await p.reload();await p.locator('#view-journal').click();assert.equal(await p.locator('textarea[data-reflection]').inputValue(),'Check paid conversion first.');await p.locator('#view-report').click();assert.equal(await p.locator('#action-report>.p-report-section').count(),10);const pending=p.waitForEvent('download');await p.locator('#export-plan').click();const f=await pending;assert.match(await fs.readFile(await f.path(),'utf8'),/Next three actions/);
 });
 await check('AI unavailable and malformed outputs visibly fall back; validated six-role AI advice is read-only',async()=>{
  await p.goto(base+'/module4/?mode=demo&lang=en&view=workspace');await p.route('https://asnm-ai.chloehappylee.workers.dev/**',r=>r.fulfill({status:503,body:'{}',contentType:'application/json'}));await p.locator('#enable-ai').check();await p.locator('[data-option]').first().click();await p.locator('#team-discussion').waitFor();assert.match(await p.locator('#advisor-mode').innerText(),/AI unavailable/);await p.unroute('https://asnm-ai.chloehappylee.workers.dev/**');await p.route('https://asnm-ai.chloehappylee.workers.dev/**',r=>r.fulfill({body:JSON.stringify({content:'invalid'}),contentType:'application/json'}));await p.locator('[data-option]').nth(1).click();await p.locator('#team-discussion').waitFor();assert.match(await p.locator('#advisor-mode').innerText(),/AI unavailable/);await p.unroute('https://asnm-ai.chloehappylee.workers.dev/**');const response={turns:['CTO','CFO','Growth','Product','Customer','Investor'].map((role,i)=>({role,replyTo:i?'CTO':'Founder',text:role+' tests a distinct assumption.'})),summary:{agreement:'Test evidence.',disagreement:'Time or cash?',tradeoff:'Speed and fixed costs.',question:'What would disprove it?'},financialState:{cash:1e12}};await p.route('https://asnm-ai.chloehappylee.workers.dev/**',r=>r.fulfill({body:JSON.stringify({discussion:response}),contentType:'application/json'}));const before=await engineState(p);await p.locator('[data-option]').last().click();await p.locator('#team-discussion').waitFor();assert.match(await p.locator('#advisor-mode').innerText(),/AI team advice/);assert.deepEqual((await engineState(p)).state,before.state);assert.deepEqual((await engineState(p)).history,before.history);await p.unroute('https://asnm-ai.chloehappylee.workers.dev/**');
 });
 await check('390px home/world/discussion/compare/report have no horizontal overflow',async()=>{
  await p.setViewportSize({width:390,height:844});await p.goto(base+'/');await p.locator('#demo-start').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(out)await p.screenshot({path:path.join(out,'v4-home-mobile.png'),fullPage:true});await p.locator('#demo-start').click();await p.goto(p.url()+'&view=workspace');await p.waitForFunction(()=>document.querySelector('#living-world')?.dataset.ready==='true');await p.locator('[data-option]').first().click();await p.locator('#team-discussion').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(out)await p.screenshot({path:path.join(out,'v4-world-mobile.png'),fullPage:true});for(const tab of ['compare','report']){await p.locator('#view-'+tab).click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
 });
 await check('text speech fallback, keyboard controls, feedback export and multi-tab conflict',async()=>{
  await p.getByRole('button',{name:/^(Feedback|피드백)$/}).click();await p.locator('dialog input').first().fill('Test decisions before spending.');const pending=p.waitForEvent('download');await p.getByRole('button',{name:/^(Save feedback|피드백 저장)$/}).click();const feedbackFile=await pending;const feedback=JSON.parse(await fs.readFile(await feedbackFile.path(),'utf8'));assert.equal(Object.keys(feedback.answers).length,5);assert.equal(feedback.answers.q0,'Test decisions before spending.');
  await p.locator('#view-decision').click();await p.evaluate(()=>{window.SpeechRecognition=undefined;window.webkitSpeechRecognition=undefined;});await p.locator('#speak-button').click();assert.match(await p.locator('#product-status').innerText(),/unavailable|지원하지/);await p.locator('[data-option]').first().focus();await p.keyboard.press('Enter');await p.locator('#team-discussion').waitFor();const other=await context.newPage();await other.goto(p.url());await other.locator('[data-option]').last().click();await other.locator('#team-discussion').waitFor();await other.locator('#commit-decision').click();await p.waitForFunction(()=>document.querySelector('#product-status').textContent.includes('Another tab')||document.querySelector('#product-status').textContent.includes('다른 탭'));assert.equal(await p.locator('[data-option]').first().isDisabled(),true);await other.close();
 });
 await check('full KO/EN journey keeps scoring, provenance, new-world handoff and original report restore',async()=>{
  for(const prefix of ['', '/en']){
   const fresh=await browser.newContext({viewport:{width:1440,height:1000}});await fresh.route('https://fonts.googleapis.com/**',r=>r.fulfill({body:''}));if(process.env.ASNM_CHART_JS_PATH)await fresh.route('https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.0/chart.umd.min.js',r=>r.fulfill({path:process.env.ASNM_CHART_JS_PATH,contentType:'application/javascript'}));
   const l=await fresh.newPage();const issues=[];l.on('pageerror',e=>{issues.push(e.message);console.error(e.stack);});await l.goto(base+prefix+'/');await l.locator('#page-home .p-entry-choice').first().click();await l.locator('.p-journey-prompt button').click();assert.equal(await l.locator('#page-m1').isVisible(),true);await l.locator('#trend-grid-ai .trend-block').first().click();await l.locator('.p-journey-nav button').nth(1).click();await l.evaluate(()=>{startDnaQuiz();quizAnswers=['T','T','A','T','V','T','S','T','A','T'];showFounderResult();});await l.locator('.p-journey-nav button').nth(2).click();
   for(const [id,value]of Object.entries({'barl-q1':'80','barl-q2':'15','barl-q3':'6','barl-q4':'Cash','barl-q5':'Demand','barl-q6':'Team'}))await l.locator('#'+id).fill(value);await l.locator('[onclick="completeBarl()"]').click();await l.locator('#s-name').fill(prefix?'Journey English':'여정 검증');await l.locator('#s-vision').fill('Make education more accessible.');await l.locator('#sim-0 [onclick="simNext()"]').click();await l.locator('#sim-1 .choice-card').first().click();await l.locator('#s-persona').fill('Teachers designing AI lessons');await l.locator('#sim-1 [onclick="simNext()"]').click();await l.locator('#sim-2 .choice-card').first().click();await l.locator('#sim-2 [onclick="simNext()"]').click();await l.locator('#sim-3 .choice-card').first().click();await l.locator('#sim-3 [onclick="simNext()"]').click();await l.locator('#sim-4 .choice-card').first().click();await l.locator('[onclick="runSimulation()"]').click();await l.waitForFunction(()=>document.querySelector('#venture-world-status').textContent.length>0);const score=Number(await l.locator('#survival-pct').innerText());assert.ok(score>=12&&score<=97);await l.locator('#sim-result [data-venture-world]').click();await l.locator('#setup-idea').waitFor();assert.equal(await l.locator('#setup-cash').inputValue(),'100000000');await l.locator('#review-start').click();await l.locator('#enter-decision-world').click();await l.locator('[data-option]').last().click();await l.locator('#team-discussion').waitFor();await l.locator('#commit-decision').click();await l.locator('#decision-outcome').waitFor();const result=await engineState(l);assert.equal(result.state.provenance.module3.survival_score,score);assert.equal(result.state.provenance.module3.trends.length,1);assert.equal(result.state.founder.decisionOrientation,'T');await l.locator('#view-report').click();await l.locator('#action-report a.p-button').last().click();await l.locator('#page-result.active').waitFor();assert.equal(Number(await l.locator('#survival-pct').innerText()),score);assert.match(await l.locator('#report-company-title').innerText(),prefix?/Journey English/:/여정 검증/);assert.deepEqual(issues,[]);await fresh.close();
  }
 });
 await check('lost WebGL context falls back without interrupting a decision',async()=>{
  const ctx=await browser.newContext({viewport:{width:1280,height:900}});const page=await ctx.newPage();const problems=[];page.on('pageerror',e=>problems.push(e.message));await page.goto(base+'/module4/?mode=demo&lang=en&view=workspace');await page.waitForFunction(()=>document.querySelector('#living-world')?.dataset.ready==='true');await page.evaluate(()=>{const canvas=document.getElementById('living-world');const gl=canvas.getContext('webgl2')||canvas.getContext('webgl');gl.getExtension('WEBGL_lose_context').loseContext();});await page.locator('#webgl-fallback').waitFor();await page.locator('[data-option]').last().click();await page.locator('#team-discussion').waitFor();await page.locator('#commit-decision').click();await page.locator('#decision-outcome').waitFor();assert.equal((await engineState(page)).history.length,1);assert.deepEqual(problems,[]);await ctx.close();
 });
 await check('non-WebGL and blocked-storage modes complete a decision',async()=>{
  const fallback=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});await fallback.addInitScript(()=>{const old=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(['webgl','webgl2','experimental-webgl'].includes(type))return null;return old.call(this,type,...args);};Object.defineProperty(window,'localStorage',{get(){throw new Error('blocked storage');}});});const f=await fallback.newPage();await f.goto(base+'/module4/?mode=demo&lang=en&view=workspace');await f.locator('#webgl-fallback').waitFor();await f.locator('[data-option]').last().click();await f.locator('#team-discussion').waitFor();await f.locator('#commit-decision').click();await f.locator('#decision-outcome').waitFor();assert.equal(await f.locator('#decision-outcome ol li').count(),3);assert.equal(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await fallback.close();
 });
 assert.deepEqual(errors,[]);console.log(`${passed.length} browser acceptance groups passed`);await context.close();await browser.close();server.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();if(server)server.close();process.exit(1)});

