const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),serve=require('./server.cjs');
let browser,server;const passed=[];
const state=p=>p.evaluate(()=>{const key=Object.keys(localStorage).find(k=>k.endsWith(':module4:v1:demo'));return JSON.parse(localStorage.getItem(key));});
async function check(name,fn){await fn();passed.push(name);console.log('PASS',name);}
(async()=>{const site=await serve();server=site.server;const base=site.base;browser=await chromium.launch({headless:true,executablePath:process.env.ASNM_BROWSER_PATH,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
for(const lang of ['ko','en']){
 const ctx=await browser.newContext({viewport:{width:1440,height:1000}});await ctx.route('https://fonts.googleapis.com/**',r=>r.fulfill({body:''}));await ctx.route('https://cdnjs.cloudflare.com/**',r=>r.fulfill({path:process.env.ASNM_CHART_JS_PATH,contentType:'application/javascript'}));const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const url=base+(lang==='en'?'/en/':'/');
 await check(lang+' minimal landing, palette, three entries and no home 3D',async()=>{await p.goto(url);await p.locator('#demo-start').waitFor();assert.equal(await p.locator('#page-home .p-entry-choice:visible').count(),3);assert.equal(await p.locator('#page-home h1:visible').count(),1);assert.equal(await p.locator('.p-preview:visible,.p-research:visible,#startup-copilot:visible').count(),0);assert.equal(await p.evaluate(()=>typeof BABYLON),'undefined');assert.equal(await p.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(2, 8, 24)');assert.equal(await p.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+2),true);});
 await check(lang+' full journey displays four modules and asks to start Module 1',async()=>{await p.locator('#page-home .p-entry-choice').first().click();await p.locator('#page-journey.active').waitFor();assert.equal(await p.locator('#page-journey [data-module]').count(),4);assert.equal(await p.locator('#page-home').isVisible(),false);await p.reload();await p.locator('#page-journey.active').waitFor();await p.locator('.p-journey-prompt button').click();await p.locator('#page-m1.active').waitFor();await p.goBack();await p.locator('#page-journey.active').waitFor();await p.locator('#page-journey .p-entry-back').click();});
 await check(lang+' question screen, typed routing, ambiguity and safe rendering',async()=>{await p.locator('#page-home .p-entry-choice').nth(1).click();assert.equal(await p.locator('#page-questions [data-module]').count(),4);await p.locator('#entry-question').fill('help me');await p.locator('.p-question-form button').click();assert.equal(await p.locator('#page-questions').isVisible(),true);assert.ok((await p.locator('#question-route-status').innerText()).length>20);for(const [q,id] of [['Which customers should I interview?','m1'],['What are my founder strengths?','m2'],['Test my business model assumptions','m3a']]){await p.locator('#entry-question').fill(q);await p.locator('.p-question-form button').click();await p.locator('#page-'+id+'.active').waitFor();await p.goBack();await p.locator('#page-questions.active').waitFor();}await p.locator('#entry-question').fill('<img src=x onerror=alert(1)> Should I hire a developer?');await p.locator('.p-question-form button').click();await p.locator('#quick-setup').waitFor();assert.match(await p.locator('#product-content').innerText(),/Should I hire/);assert.equal(await p.locator('#product-content img').count(),0);});
 await check(lang+' guided demo: six stages, sequential viewpoints, refresh and one commit',async()=>{await p.goto(base+'/module4/?mode=demo&lang='+lang);await p.locator('#demo-begin').waitFor();assert.equal(await p.locator('#view-report:visible,#living-world:visible,input:visible,textarea:visible').count(),0);await p.locator('#demo-begin').click();assert.equal(await p.locator('[data-option]').count(),3);await p.locator('[data-option="developer"]').click();await p.locator('[data-demo-stage="discussion"]').waitFor();await p.waitForFunction(()=>document.querySelector('#living-world')?.dataset.ready==='true');assert.equal(await p.locator('.p-turn:visible').count(),1);await p.setViewportSize({width:390,height:844});await p.waitForTimeout(200);assert.equal(await p.locator('#agent-bubble').evaluate(n=>{const b=n.getBoundingClientRect(),s=n.parentElement.getBoundingClientRect();return b.bottom<=s.bottom&&b.right<=s.right;}),true);await p.setViewportSize({width:1440,height:1000});await p.locator('#demo-next-turn').click();await p.reload();await p.locator('[data-demo-stage="discussion"]').waitFor();assert.match(await p.locator('#team-discussion').innerText(),/2 \/ 6/);for(let i=0;i<5;i++)await p.locator('#demo-next-turn').click();await p.locator('[data-demo-stage="summary"]').waitFor();assert.equal((await state(p)).history.length,0);await p.locator('#commit-decision').click();await p.locator('[data-demo-stage="result"]').waitFor();assert.equal(await p.locator('.p-demo-result').count(),3);assert.equal((await state(p)).history.length,1);assert.equal((await state(p)).decisionJournal[0].expectedGrowth,null);await p.reload();await p.locator('[data-demo-stage="result"]').waitFor();assert.equal((await state(p)).history.length,1);await p.locator('#demo-next-action').click();assert.equal(await p.locator('.p-demo-actions li').count(),3);await p.locator('#demo-compare').click();await p.locator('#comparison-results table').waitFor();assert.equal((await state(p)).history.length,1);assert.equal(await p.locator('body').evaluate(n=>n.classList.contains('p-guided-demo')),false);});
 await check(lang+' 390px screens, keyboard and light theme',async()=>{await p.setViewportSize({width:390,height:844});await p.goto(url);await p.locator('#demo-start').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.locator('#theme-toggle').click();assert.equal(await p.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(255, 255, 255)');await p.locator('#theme-toggle').click();await p.locator('#page-home .p-entry-choice').first().focus();await p.keyboard.press('Enter');await p.locator('#page-journey.active').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);if(process.env.ASNM_SCREENSHOT_DIR){await fs.mkdir(process.env.ASNM_SCREENSHOT_DIR,{recursive:true});await p.screenshot({path:process.env.ASNM_SCREENSHOT_DIR+'/'+lang+'-journey-mobile.png',fullPage:true});}await p.locator('#page-journey .p-entry-back').click();await p.locator('#page-home .p-entry-choice').nth(1).click();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.locator('#page-questions .p-entry-back').click();if(process.env.ASNM_SCREENSHOT_DIR)await p.screenshot({path:process.env.ASNM_SCREENSHOT_DIR+'/'+lang+'-home-mobile.png',fullPage:true});assert.deepEqual(errors,[]);});
 await ctx.close();
}
await check('390px no-WebGL + blocked storage still completes guided decision and action',async()=>{const ctx=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});await ctx.addInitScript(()=>{const old=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(t,...args){return /webgl/.test(t)?null:old.call(this,t,...args);};Object.defineProperty(window,'localStorage',{get(){throw Error('blocked');}});Object.defineProperty(window,'sessionStorage',{get(){throw Error('blocked');}});});const p=await ctx.newPage();await p.goto(base+'/module4/?mode=demo&lang=ko');await p.locator('#demo-begin').click();await p.locator('[data-option="discover"]').click();await p.locator('#webgl-fallback').waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);for(let i=0;i<6;i++)await p.locator('#demo-next-turn').click();await p.locator('#commit-decision').click();await p.locator('#demo-next-action').click();assert.equal(await p.locator('.p-demo-actions li').count(),3);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await ctx.close();});
console.log(passed.length+' entry/demo browser groups passed');await browser.close();server.close();})().catch(async e=>{console.error(e);if(browser)await browser.close();if(server)server.close();process.exit(1)});
