import {el,fmt,money} from './dom.js';
import {roles,missions,roomCategories,experienceState,ready} from '../experience/MissionDirector.js';
import {dialogue,choicesFor,tradeoff} from '../experience/DialogueDirector.js';
import {decisions} from '../simulation/DecisionEngine.js';
import {rooms} from '../world/rooms.js';
export function selectRole(lang,onEnter){
 const t=(ko,en)=>lang==='ko'?ko:en,modal=el('dialog',{id:'role-dialog','aria-labelledby':'role-title'});
 const select=el('select',{id:'player-role'},...Object.entries(roles).map(([v,label])=>el('option',{value:v,text:label[lang==='ko'?1:0]})));
 modal.append(el('div',{class:'eyebrow',text:'YOUR VENTURE · YOUR PERSPECTIVE'}),el('h2',{id:'role-title',text:t('어떤 역할로 시작할까요?','Choose your role')}),el('label',{},t('플레이어 역할','Player role'),select),el('p',{text:t('역할은 대화와 미션 우선순위에만 영향을 줍니다. 모든 결정을 할 수 있으며 계산 규칙은 같습니다.','Your role changes dialogue and mission priorities only. All decisions remain available and calculation rules stay the same.')}),el('button',{id:'confirm-role',class:'primary',text:t('내 Venture 입장','Enter my venture'),onclick:()=>{modal.close();modal.remove();onEnter(select.value);}}));
 document.body.append(modal);modal.showModal();
}
export function createImmersive({host,missionHost,lang,getSession,save,getWorld,go,commit,canCommit,advanced,dashboard,sync}){
 const t=(ko,en)=>lang==='ko'?ko:en;let room='ceo',pending=null,review=false,busy=false,outcomeStep=0,animation=0;
 const names={hiring:t('채용','Hiring'),product:t('제품','Product'),marketing:t('마케팅','Marketing'),pricing:t('가격','Pricing'),fundraising:t('투자유치','Fundraising'),market:t('시장','Market')};
 const name=(c,a)=>decisions[c].find(o=>o[0]===a)?.[lang==='ko'?1:2]||a;
 const state=()=>getSession().state;
 const exp=()=>{const s=getSession();s.experience=experienceState(s.experience,s.state);return s.experience;};
 const persist=()=>{save();sync(exp());};
 const button=(id,text,fn,primary=false)=>el('button',{id,text,onclick:fn,class:primary?'primary':''});
 function portrait(speaker,mood){return el('div',{class:'speaker-portrait','data-mood':mood,'aria-hidden':'true'},el('span',{class:'portrait-hair'}),el('span',{class:'portrait-face'}),el('span',{class:'portrait-jacket'}),el('small',{text:speaker.split(' ').map(s=>s[0]).slice(0,2).join('')}));}
 function shell(d){host.replaceChildren(el('div',{class:'dialogue-person'},portrait(d.portrait,d.mood),el('div',{},el('div',{class:'eyebrow',text:t('시나리오 대화 · 결정은 당신의 몫','SCENARIO DIALOGUE · YOU DECIDE')}),el('h2',{text:d.speaker}),el('span',{class:'mood-label',text:d.mood.toUpperCase()}))),el('p',{class:'dialogue-text',text:d.text}));if(d.context)host.append(el('details',{class:'dialogue-context'},el('summary',{text:t('내가 입력한 가정 보기','Your recorded assumptions')}),el('p',{text:d.context})));}
 function assumption(){const x=exp(),input=el('textarea',{id:'dialogue-assumption',maxlength:2000,placeholder:t('이번 달 검증할 가정…','An assumption to test this month…')});input.value=x.reason;input.addEventListener('input',()=>{exp().reason=input.value;persist();});return el('label',{class:'assumption-input'},t('CEO: 이번 결정에서 검증할 가정은 무엇인가요?','CEO: What assumption will you test with these decisions?'),input,el('small',{text:t('기록만 저장하며 계산값을 임의 변경하지 않습니다.','Saved to the decision log; this note does not change numeric inputs.')}));}
 function allDecisions(){const x=exp();return el('div',{class:'review-grid'},...Object.entries(x.choices).map(([c,a])=>el('div',{},el('strong',{text:names[c]}),el('span',{text:name(c,a)}),el('small',{text:x.confirmed.includes(c)?t('직접 확인한 선택','Confirmed by you'):t('기존 기본 선택 · 미확인','Existing default · not confirmed')}))));}
 function render(){
  const s=state(),x=exp();cancelAnimationFrame(animation);renderMissions();
  if(x.phase==='outcome'&&getSession().history.length){renderOutcome();return;}
  if(busy){shell({speaker:roles[x.role][lang==='ko'?1:0],portrait:'You',mood:'walk',text:t('선택한 공간으로 걸어가고 있습니다…','Walking to your chosen room…')});return;}
  const d=dialogue(s,room,lang);shell(d);getWorld()?.conversation(room,pending?'think':d.mood);
  if(!x.seenRooms.includes(room))host.append(el('div',{class:'context-guide'},el('p',{text:t(`${rooms.find(r=>r.id===room)[lang]}에서 상황을 듣고 선택을 검토하세요. 선택 후 영향을 확인하고 확정합니다.`,`In ${rooms.find(r=>r.id===room).name}, hear the situation, choose an action, review the trade-off, then confirm.`)}),button('guide-got-it',t('알겠어요','Got it'),()=>{exp().seenRooms.push(room);persist();render();})));
  if(pending){host.append(el('h3',{text:name(pending.category,pending.action)}),el('p',{class:'tradeoff',text:tradeoff(pending.category,pending.action,lang)}),el('p',{class:'small',text:t(`통화 단위 = ${s.costUnit}. 즉시 효과 설명이며 월말 이벤트·운영·상한 적용 후 결과는 달라질 수 있습니다.`,`Currency unit = ${s.costUnit}. Immediate effects only; month-end events, operations and bounds also affect outcomes.`)}),button('confirm-decision',t('결정 확정','Confirm decision'),()=>{const next=exp();next.choices[pending.category]=pending.action;if(!next.confirmed.includes(pending.category))next.confirmed.push(pending.category);pending=null;persist();render();},true),button('cancel-decision',t('다른 선택 검토','Consider another choice'),()=>{pending=null;render();}));return;}
  if(room==='ceo'){
   host.append(el('p',{class:'source-briefing',text:s.provenance?.source==='module3'?t('이 World는 Module 3 데이터와 공개된 변환 가정으로 생성되었습니다.','This world was created from Module 3 data and disclosed conversion assumptions.'):s.provenance?.source==='standalone'?t('이 World는 Standalone 입력과 기본 가정으로 생성되었습니다.','This world was created from standalone inputs and default assumptions.'):t('샘플 / 가져온 시나리오 가정으로 시작합니다.','This world uses sample / imported scenario assumptions.')}));
   host.append(el('p',{class:'role-focus',text:t('현재 역할: ','Your perspective: ')+roles[x.role][lang==='ko'?1:0]+' · '+({ceo:t('전체 전략과 최종 선택을 함께 검토하세요.','Review overall strategy and the final choices.'),product:t('제품 준비도와 기술부채를 먼저 살펴보세요.','Start with product readiness and technical debt.'),growth:t('고객 유지율, 시장과 CAC를 먼저 살펴보세요.','Start with retention, market demand and CAC.'),finance:t('현금, 월 비용과 자금조달을 먼저 살펴보세요.','Start with cash, burn and financing.')})[x.role]}));
   const last=getSession().history.at(-1);if(last)host.append(el('p',{text:t('지난달 실제 이벤트: ','Last simulated event: ')+last.event[lang]}));
   if(x.phase==='briefing')host.append(button('start-month',t(`Month ${s.simulation.currentMonth+1} 시작`,`Start month ${s.simulation.currentMonth+1}`),()=>{exp().phase='active';persist();render();},true));
   else {host.append(assumption());if(ready(s,x)||review){host.append(allDecisions(),el('p',{class:'small',text:t('미확인 분야에는 기존 기본값이 적용됩니다. 기본 제품 개선도 비용을 지출하며 시장 집중은 수요를 바꿉니다.','Unconfirmed categories use existing defaults. Default product improvement spends cash, and focusing the market changes demand.')}));if(!ready(s,x))host.append(el('p',{text:t('필수 미션을 확인한 뒤 확정할 수 있습니다.','Confirm the required missions before committing.')}));const b=button('commit-month',t('검토 완료 · 한 달 실행','Commit month'),()=>{if(!ready(state(),exp())||!canCommit())return;sync(exp());commit();},true);b.disabled=!ready(s,x)||!canCommit();host.append(b);}else host.append(el('p',{text:t('미션을 마친 뒤 이곳으로 돌아와 6개 결정을 검토하세요.','Complete the missions and return here to review all six decisions.')}));}
  }else if(x.phase==='briefing')host.append(button('return-briefing',t('CEO 브리핑에서 이번 달 시작','Start this month at the CEO briefing'),()=>go('ceo'),true));
  else for(const category of roomCategories[room])host.append(el('h3',{text:names[category]+(x.confirmed.includes(category)?' ✓':'')}),el('div',{class:'dialogue-choices'},...choicesFor(s,category,lang).map(({action,label})=>button(`choose-${category}-${action}`,label,()=>{pending={category,action};render();}))));
  if(room!=='ceo')host.append(button('finish-conversation',t('대화 마치기','Finish conversation'),()=>{getWorld()?.focus(room);host.replaceChildren(button('reopen-conversation',t('다시 대화하기','Talk again'),render));}));
 }
 function renderMissions(){
  const s=state(),x=exp(),list=missions(s,x.role),count=list.filter(m=>x.confirmed.includes(m.category)).length;
  missionHost.replaceChildren(el('div',{class:'eyebrow',text:`MONTH ${String(s.simulation.currentMonth+1).padStart(2,'0')} · ${roles[x.role][0]}`}),el('h2',{text:t('이번 달의 목표','Your monthly objectives')}),el('div',{class:'mission-count',text:`${count} / ${list.length}`}),el('p',{text:t('상태와 역할에 따른 우선 검토 과제입니다. 모든 분야를 추가로 검토할 수 있습니다.','Priorities reflect state and role. You can also review every other category.')}));
  for(const m of list){const done=x.confirmed.includes(m.category);missionHost.append(el('button',{class:'mission-item','data-mission':m.category,onclick:()=>go(m.room)},el('span',{text:done?'✓':'○'}),el('span',{},el('strong',{text:names[m.category]}),el('small',{text:done?name(m.category,x.choices[m.category]):rooms.find(r=>r.id===m.room)[lang]}))));}
  const next=list.find(m=>!x.confirmed.includes(m.category));
  missionHost.append(button('next-mission',x.phase==='briefing'?t('CEO 브리핑으로','Go to CEO briefing'):next?t('다음 공간: ','Next: ')+rooms.find(r=>r.id===next.room)[lang]:t('CEO에게 돌아가 검토','Return to CEO for review'),()=>go(x.phase==='briefing'?'ceo':next?.room||'ceo'),true),button('view-decisions',t('전체 결정 보기','View all decisions'),()=>{review=true;go('ceo');}),button('open-advanced',t('고급 결정 시트','Advanced Decision Sheet'),advanced),button('open-dashboard',t('대시보드 열기','Open Dashboard'),dashboard),button('open-tutorial',t('도움말 / 튜토리얼','Help / Tutorial'),tutorial));
  const notices=[];if(s.venture.runway!==null&&s.venture.runway<6)notices.push(['finance',t('CFO: 현금 여력을 함께 검토해요.','CFO wants to discuss low runway.')]);if(s.venture.retention<60)notices.push(['customer',t('고객: 이탈이 우려됩니다.','Customer: retention needs attention.')]);if(s.operations.offer)notices.push(['investor',t('투자자: 새 조건이 도착했습니다.','Investor: an offer is available.')]);
  for(const [id,text] of notices)missionHost.append(el('div',{class:'npc-notification','data-notification':id},el('p',{text}),button('notice-'+id,t('이동','Go'),()=>go(id))));
  if(!canCommit())missionHost.append(el('p',{class:'notice',text:t('현금 소진·60개월 종료·다른 탭 변경 시 실행할 수 없습니다. 상태 메시지와 리포트를 확인하세요.','Execution is unavailable after cash depletion, month 60, or another tab changing the session. Check the status and report.')}));
  getWorld()?.missions(x.phase==='active'?list.filter(m=>!x.confirmed.includes(m.category)).map(m=>m.room):['ceo']);
 }
 function tutorial(){
  const modal=el('dialog',{id:'tutorial-dialog','aria-labelledby':'tutorial-title'});let step=0;const source=state().provenance?.source;
  const steps=[t('당신의 Venture World에 오신 것을 환영합니다. 아바타는 선택한 역할의 당신입니다.','Welcome to your Venture World. The player avatar represents you in your chosen role.'),source==='module3'?t('회사는 Module 3 데이터와 공개된 변환 가정을 바탕으로 생성되었습니다.','Your company was created from Module 3 data and disclosed conversion assumptions.'):t('회사는 입력한 시나리오와 기본 가정을 바탕으로 생성되었습니다.','Your company was created from scenario inputs and default assumptions.'),t('CEO·재무·시장·제품·고객·팀·투자 공간이 있습니다. 방 버튼 또는 3D 공간을 클릭하면 걸어갑니다.','Explore CEO, Finance, Market, Product, Customer, Team and Investor rooms. Click a room button or the 3D space to walk there.'),t('사람들과 대화하고, 영향을 살펴본 뒤 결정을 확정하세요. 필수 미션 외의 결정도 가능합니다.','Talk to people, review trade-offs, and confirm your choices. Decisions beyond the required missions are always available.'),t('CEO실에서 6개 최종 선택을 검토하고 한 달을 실행하세요. 결과를 살펴본 뒤 다음 달을 시작합니다.','Review all six final choices at the CEO office and commit the month. Observe the consequences, then continue.')];
  const done=()=>{exp().tutorialSeen=true;persist();modal.close();modal.remove();};
  const draw=()=>modal.replaceChildren(el('div',{class:'eyebrow',text:`VENTURE GUIDE · ${step+1} / 5`}),el('h2',{id:'tutorial-title',text:step===0?t('환영합니다, ','Welcome, ')+roles[exp().role][lang==='ko'?1:0]:t('내 회사를 운영하는 방법','Leading your venture')}),el('p',{text:steps[step]}),el('div',{class:'entry-actions'},button('tutorial-skip',t('건너뛰기','Skip'),done),...(step?[button('tutorial-back',t('이전','Back'),()=>{step--;draw();})]:[]),button('tutorial-next',step===4?t('시작하기','Start my venture'):t('다음','Next'),()=>{if(step===4)done();else{step++;draw();}},true)));
  modal.addEventListener('cancel',e=>{e.preventDefault();done();});document.body.append(modal);draw();modal.showModal();
 }
 function renderOutcome(){
  const log=getSession().history.at(-1),v=log.stateAfter.venture,b=log.stateBefore.venture;
  const headings=[t('30일 후…','30 days later…'),t('이번 달 시장 이벤트','This month’s market event'),t('내 결정이 만든 변화','Business outcome'),t('팀의 반응','Your team responds')];
  shell({speaker:headings[outcomeStep],portrait:'Outcome',mood:(v.runway!==null&&(v.runway<6||b.runway===null||v.runway<b.runway))||v.retention<b.retention?'concerned':v.productProgress>b.productProgress||v.mrr>b.mrr?'celebrate':'idle',text:outcomeStep===0?`MONTH ${log.month}`:outcomeStep===1?log.event[lang]:outcomeStep===2?t('결정·이벤트·운영을 모두 반영한 실제 시뮬레이션 결과입니다.','Actual simulated results after decisions, events and operations.'):t(`CFO: Runway ${fmt(b.runway)} → ${fmt(v.runway)}개월. 고객: 유지율 ${fmt(b.retention)} → ${fmt(v.retention)}%.`,`CFO: runway ${fmt(b.runway)} → ${fmt(v.runway)} months. Customer: retention ${fmt(b.retention)} → ${fmt(v.retention)}%.`)});
  if(outcomeStep>=2){const cards=el('div',{class:'outcome-grid'}),nodes=[];for(const [k,label] of [['cash','Cash'],['mrr','MRR'],['retention',t('유지율','Retention')],['runway','Runway'],['productProgress',t('제품','Product')],['teamSize',t('팀','Team')]]){const format=n=>['cash','mrr'].includes(k)?money(n,state().currency,lang):fmt(n),value=el('b',{text:format(v[k])});nodes.push({value,k,format});cards.append(el('article',{},el('span',{text:label}),value,el('small',{text:`${format(b[k])} → ${format(v[k])}`})));}host.append(cards);
   if(outcomeStep===2&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const begin=performance.now();const tick=now=>{const p=Math.min(1,(now-begin)/800);for(const {value,k,format} of nodes)if(b[k]!==null&&v[k]!==null)value.textContent=format(b[k]+(v[k]-b[k])*p);if(p<1)animation=requestAnimationFrame(tick);};animation=requestAnimationFrame(tick);}
  }
  host.append(button('outcome-next',outcomeStep===3?t('다음 달로 계속','Continue to next month'):t('계속','Continue'),()=>{if(outcomeStep<3){outcomeStep++;render();}else{exp().phase='briefing';persist();outcomeStep=0;room='ceo';go('ceo');}},true));
 }
 return {render,start(){room='ceo';pending=null;review=false;busy=false;sync(exp());render();if(!exp().tutorialSeen)tutorial();},walking(){busy=true;pending=null;render();},arrive(id){room=id;busy=false;pending=null;render();},outcome(){outcomeStep=0;busy=false;room='ceo';pending=null;review=false;exp().phase='outcome';persist();getWorld()?.overview();render();},advancedChange(category,action){const x=exp();x.choices[category]=action;if(!x.confirmed.includes(category))x.confirmed.push(category);persist();renderMissions();},canAdvance:()=>exp().phase==='active'&&room==='ceo'&&ready(state(),exp()),tutorial};
}
