import {sampleState,validateState,clone} from '../module4/state/ASNMState.js';
import {defaultDecisions,validateDecisions} from '../module4/simulation/DecisionEngine.js';
import {simulateMonth} from '../module4/simulation/SimulationEngine.js';
export const VERSION='4.0.0';
export const roles=['CEO','CTO','CFO','Growth','Product','Customer','Investor'];
export const tr=(lang,ko,en)=>lang==='ko'?ko:en;
export function demoState(){
 const s=sampleState();s.currency='KRW';s.venture={...s.venture,ventureName:'LearnLoop AI',industry:'AI Education',cash:45000000,monthlyBurn:8500000,mrr:3200000,cac:180000,retention:82,teamSize:3,teamCapacity:46,productProgress:46};
 s.market={demand:32,marketGrowth:12,competition:60,uncertainty:64};s.operations={marketingBudget:1200000,technicalDebt:28,priceMultiplier:1,founderEquity:100,offer:null};s.assumptions={};s.provenance={source:'product-demo',notes:['Illustrative AI education venture. No observed customer or financial data. All values are editable model assumptions.']};return validateState(s);
}
export function suggestState({idea,stage='idea',team='solo',funds='6-12',cash,mrr,burn,demand,retention}){
 const s=demoState();s.venture.ventureName=String(idea).trim().slice(0,120);s.venture.stage=stage;s.venture.teamSize={solo:1,small:3,large:5}[team]||1;
 s.venture.productProgress={idea:10,interview:20,mvp:46,customer:65,revenue:75,growth:85}[stage]??10;
 s.venture.mrr=['revenue','growth'].includes(stage)?3200000:0;s.venture.monthlyBurn=s.venture.teamSize*2000000+1000000;
 s.venture.cash=({'none':.5,'0-3':2,'3-6':4.5,'6-12':9,'12+':15}[funds]??9)*(s.venture.monthlyBurn-s.venture.mrr);
 s.operations.marketingBudget=s.venture.monthlyBurn*.15;s.market.demand=['customer','revenue','growth'].includes(stage)?50:25;
 for(const [key,value] of Object.entries({cash,mrr,monthlyBurn:burn,retention}))if(value!==undefined&&value!=='')s.venture[key]=Number(value);
 if(demand!==undefined&&demand!=='')s.market.demand=Number(demand);
 s.operations.marketingBudget=Math.min(s.operations.marketingBudget,s.venture.monthlyBurn);
 s.provenance={source:'standalone',description:String(idea).slice(0,2000),notes:['Starting values suggested by explicit stage/team/runway presets; not extracted facts or live market evidence. Review and edit before starting.']};s.assumptions={};return validateState(s);
}
const option=(id,ko,en,changes,whyKo,whyEn)=>({id,ko,en,changes,whyKo,whyEn});
export function decisionMoment(s,problem='priority'){
 const offer=s.operations.offer;
 if(offer)return {id:'offer',ko:'투자 제안을 수락할까요?',en:'Accept the investment offer?',options:[option('accept','투자 제안 수락','Accept offer',{fundraising:'accept'},'현금을 확보하고 창업자 지분을 희석합니다.','Adds cash and dilutes founder ownership.'),option('reject','제안 거절 · 독립 유지','Reject · stay independent',{fundraising:'reject'},'지분은 유지되지만 자금 문제는 남습니다.','Preserves ownership; cash constraints remain.')]};
 if(problem==='pricing')return {id:'pricing',ko:'가격을 올릴까요, 유지할까요?',en:'Raise prices or hold?',options:[option('raise','가격 10% 인상','Raise price 10%',{pricing:'raise'},'모델은 매출 증가와 유지율 3%p 감소를 함께 적용합니다.','The model raises revenue and lowers retention by 3 pp.'),option('hold','가격 유지 · 제품 개선','Hold · improve product',{},'가격을 유지하고 기존 고객의 경험을 개선합니다.','Preserves price while improving the existing experience.'),option('lower','가격 10% 인하','Lower price 10%',{pricing:'lower'},'고객 유지와 매출 단가 사이의 차이를 실험합니다.','Tests the trade-off between retention and revenue per customer.')]};
 if(problem==='funding')return {id:'funding',ko:'지금 외부 자금이 필요한가요?',en:'Do you need external capital now?',options:[option('fund','투자 유치 시작','Seek investment',{fundraising:'attempt'},'협상비용이 들고 제안은 보장되지 않습니다.','Costs time and cash; an offer is not guaranteed.'),option('reduce','독립 유지 · 지출 축소','Bootstrap · reduce spend',{marketing:'reduce'},'지분을 유지하면서 고객 유입 비용을 줄입니다.','Preserves ownership while reducing acquisition spending.')]};
 if(problem==='market')return {id:'market',ko:'새로운 시장에 진입할까요?',en:'Enter a new market?',options:[option('enter','신규 시장 진입','Enter new market',{market:'enter'},'확장 비용과 수요 불확실성이 증가합니다.','Adds expansion costs and demand uncertainty.'),option('test','작은 고객 실험 먼저','Test a small segment',{market:'test'},'고객 탐색을 세그먼트 테스트 규칙으로 모델링합니다.','Models discovery through the segment-test rule.'),option('focus','현재 고객에 집중','Focus current market',{},'확장 비용을 피하고 현재 시장을 학습합니다.','Avoids expansion costs and learns in the current market.')]};
 if(s.venture.runway!==null&&s.venture.runway<6)return {id:'cash',ko:'남은 자금으로 무엇을 우선할까요?',en:'What should you prioritize with limited cash?',options:[option('cut','마케팅 예산 20% 절감','Reduce marketing 20%',{marketing:'reduce'},'고객 유입과 비용이 함께 줄어듭니다.','Reduces both spending and customer acquisition.'),option('fund','투자 유치 시작','Seek investment',{fundraising:'attempt'},'비용이 먼저 들며 현금은 제안 수락 후에만 들어옵니다.','Costs come first; cash arrives only after an accepted offer.'),option('discover','고객 검증에 집중','Focus customer discovery',{market:'test'},'채용을 보류하고 작은 수요 실험을 수행합니다.','Holds hiring and runs a small demand experiment.')]};
 return {id:'priority',ko:'다음 한 달, 무엇을 먼저 하시겠습니까?',en:'What will you prioritize next month?',options:[option('developer','개발자 채용','Hire a developer',{hiring:'developer',product:'feature'},'출시 속도와 고정비가 함께 늘어납니다.','Improves delivery and increases fixed costs.'),option('marketer','마케터 채용','Hire a marketer',{hiring:'marketer',marketing:'increase'},'고객 유입을 늘리는 대신 비용이 증가합니다.','Expands acquisition while increasing costs.'),option('discover','고객 인터뷰 확대','Expand customer discovery',{market:'test'},'인터뷰는 모델의 고객 세그먼트 테스트로 표현합니다.','Interviews are represented by the model’s segment-test rule.')]};
}
export function choicesFor(state,option){const c={...defaultDecisions(),...option.changes};if(state.venture.teamSize>=100)c.hiring='hold';validateDecisions(c,state);return c;}
export function compareScenarios(state,a,b){return [a,b].map(o=>({option:o,choices:choicesFor(state,o),...simulateMonth(clone(state),choicesFor(state,o),'counterfactual','')}));}
export function discussion(state,option,lang='ko',user=''){
 const t=(ko,en)=>tr(lang,ko,en),v=state.venture,m=state.market,projected=simulateMonth(state,choicesFor(state,option)).state,runway=projected.venture.runway===null?'∞':projected.venture.runway;
 return {source:'rules',turns:[
 {role:'CTO',replyTo:'Founder',text:t(`「${option.ko}」는 제품 완성도를 ${v.productProgress}에서 ${projected.venture.productProgress}로 바꿉니다. 속도가 고객 문제 해결로 이어지는지 확인해야 합니다.`,`“${option.en}” changes modeled product readiness from ${v.productProgress} to ${projected.venture.productProgress}. Does delivery solve the customer’s problem?`)},
 {role:'CFO',replyTo:'CTO',text:t(`CTO의 속도 제안에는 비용도 있습니다. 전체 선택과 이번 달 이벤트를 적용한 Runway는 ${runway}개월입니다.`,`CTO’s delivery argument comes with costs. With the full choices and this month’s event, modeled runway is ${runway} months.`)},
 {role:'Growth',replyTo:'CTO',text:t(`출시 속도보다 수요 신호 ${m.demand}/100의 근거부터 확인하고 싶습니다. 채널별 유료 전환을 작은 실험으로 측정하세요.`,`Before CTO’s delivery priority, I would question the evidence behind demand ${m.demand}/100. Measure paid conversion in a small channel test.`)},
 {role:'Product',replyTo:'Growth',text:t('Growth의 검증 제안에 동의합니다. 가장 반복되는 고객 문제 하나를 제품 우선순위와 연결하세요.','I agree with Growth’s evidence check. Connect one recurring customer problem to the product priority.')},
 {role:'Customer',replyTo:'Product',text:t(`Product의 우선순위가 제 문제를 해결해야 계속 결제할 이유가 생깁니다. 현재 유지율 ${v.retention}%는 사용자 가정인지 관측값인지 확인하세요.`,`Product’s priority must solve my problem to earn renewal. Check whether retention ${v.retention}% is an assumption or observed data.`)},
 {role:'Investor',replyTo:'CFO',text:t(`CFO의 현금 제약과 고객 증거를 함께 보겠습니다. 현재 창업자 지분 ${state.operations.founderEquity}%에서 어떤 성과를 위해 자본을 쓰나요?`,`I would combine CFO’s cash constraint with customer evidence. With founder ownership ${state.operations.founderEquity}%, which milestone warrants the capital?`)}],
 summary:{agreement:t('비용을 쓰기 전에 측정할 고객 증거를 정합니다.','Define measurable customer evidence before spending.'),disagreement:t('개발 속도와 고객 검증 중 무엇을 먼저 할지 의견이 다릅니다.','Delivery speed and customer validation compete for priority.'),tradeoff:t(option.whyKo,option.whyEn),question:t('이번 결정이 틀렸다는 것을 어떤 결과로 알 수 있나요?','What result would show that this decision was wrong?')},user};
}
export function actionPlan(session,lang='ko'){
 const t=(ko,en)=>tr(lang,ko,en),s=session.state,cash=s.venture.runway!==null&&s.venture.runway<6,pricing=session.history.at(-1)?.decisions.some(d=>d.category==='pricing'&&d.action==='raise');
 return {risk:cash?t('남은 자금과 고정비','Cash runway and fixed costs'):s.market.uncertainty>50?t('고객 수요의 불확실성','Uncertain customer demand'):t('고객 유지와 반복 구매','Retention and repeat purchase'),assumptions:[t('수요 지표는 실제 시장 점유율이 아닌 모델 입력값입니다.','Demand is a model input, not observed market share.'),t('고객 유지율과 획득비용을 실제 기록으로 확인해야 합니다.','Validate retention and acquisition costs against actual records.'),t('가격·채용 효과는 공개된 규칙으로 정해집니다.','Pricing and hiring effects follow published rules.')],week:[t('1–2일: 목표 고객 5명을 정하고 가장 최근 겪은 문제를 인터뷰하세요.','Days 1–2: interview five target customers about their most recent problem.'),pricing?t('3–4일: 기존 고객 5명에게 새 가격의 지불 의사를 확인하세요.','Days 3–4: test willingness to pay at the new price with five existing customers.'):t('3–4일: 핵심 문제 하나를 위한 작은 유료 제안 또는 MVP를 시험하세요.','Days 3–4: test a small paid offer or MVP for one core problem.'),cash?t('5–7일: 고정비·현금·매출을 확인하고 다음 지출의 중단 기준을 정하세요.','Days 5–7: reconcile expenses, cash and revenue; set a stop rule for spending.'):t('5–7일: 전환·재사용·지불 의사를 기록하고 다음 결정의 기준을 정하세요.','Days 5–7: record conversion, reuse and willingness to pay; define a decision threshold.')],month:t('1주 고객 문제 확인 → 2주 작은 제안 테스트 → 3주 유료 전환·유지 관찰 → 4주 가정을 수정하고 같은 결정 재실험.','Week 1 problem interviews → week 2 small offer → week 3 observe paid conversion and retention → week 4 revise assumptions and rerun the decision.'),measure:t('인터뷰의 반복 문제 수, 실제 유료 전환율, 고객 유지율, CAC, 순현금소진. 각 지표의 관측 기간과 표본 수를 기록하세요.','Measure recurring problems, observed paid conversion, retention, CAC and net cash burn. Record the period and sample size.'),revisit:t('실제 고객 증거 또는 비용이 달라지면 이번 우선순위를 다시 비교하세요.','Revisit this priority when actual customer evidence or costs change.')};
}
export function journalInsight(session,lang='ko'){
 const rows=session.decisionJournal||[],valid=rows.filter(r=>Number.isFinite(r.expectedGrowth)&&Number.isFinite(r.modeledGrowth));
 if(valid.length<3)return tr(lang,'성장 예상치를 입력한 결정 3개가 쌓이면 모델 결과와의 차이를 돌아볼 수 있습니다. 실제 성과 검증과는 별개입니다.','After three decisions with growth expectations, review their gaps to modeled outcomes. This is separate from validation against actual results.');
 const gap=valid.reduce((sum,r)=>sum+r.expectedGrowth-r.modeledGrowth,0)/valid.length;
 return tr(lang,`${valid.length}개 결정에서 예상 MRR 성장률은 모델 결과보다 평균 ${Math.abs(gap).toFixed(1)}%p ${gap>=0?'높았습니다':'낮았습니다'}. 실제 시장 결과나 성격 진단을 의미하지 않습니다.`,`Across ${valid.length} decisions, expected MRR growth averaged ${Math.abs(gap).toFixed(1)} pp ${gap>=0?'above':'below'} modeled growth. This is not actual market performance or a personality diagnosis.`);
}
