import {copilotView} from './copilot.js';
import {StateStore} from '../module4/state/StateStore.js';
import {el} from '../module4/ui/dom.js';
import {track} from './telemetry.js';
const lang=document.documentElement.lang==='en'?'en':'ko',t=(ko,en)=>lang==='ko'?ko:en;
const root=new URL('../',import.meta.url),world=(problem='',mode='')=>new URL(`module4/?lang=${lang}${problem?'&problem='+problem:''}${mode?'&mode='+mode:''}`,root).href;
const home=document.getElementById('page-home');
const problems=[['market',t('💡 내 아이디어가 시장에서 통할지 궁금해요','💡 Will my idea solve a market need?'),'m1'],['customer',t('🔎 어떤 고객부터 만나야 할지 모르겠어요','🔎 Which customers should I interview?'),'m1'],['founder',t('🧬 내 의사결정 스타일을 알고 싶어요','🧬 Understand my decision style'),'m2'],['priority',t('🧭 지금 무엇부터 해야 할지 모르겠어요','🧭 What should I do first?')],['budget',t('💰 개발·채용·마케팅, 어디에 돈을 쓸까요?','💰 Development, hiring or marketing?')],['pricing',t('💵 가격을 올릴까요, 유지할까요?','💵 Raise prices or hold?')],['funding',t('🤝 지금 투자를 받아야 할까요?','🤝 Should I raise investment now?')],['market',t('🚀 새로운 시장에 들어가야 할까요?','🚀 Should I enter a new market?')],['simulate',t('🎮 내 결정을 미리 실험하고 싶어요','🎮 Simulate my next decision')]];
function navigate(id){window.showPage(id);track('quick_start');}
const button=(text,fn,cls='')=>el('button',{class:cls,text,onclick:fn});
home.classList.add('asnm-product');
const legacy=document.createElement('details');legacy.hidden=true;while(home.firstChild)legacy.append(home.firstChild);home.append(legacy);
const hero=el('section',{class:'p-wrap p-hero'},el('div',{},el('div',{class:'p-kicker',text:'ASNM / AI VENTURE DECISION SIMULATOR'}),el('h1',{text:t('실제 돈과 시간을 쓰기 전에,\n다음 결정을 먼저 실험하세요.','Test your startup decisions before you spend real money.')}),el('p',{class:'p-lead',text:t('시장과 창업자, 사업 리스크를 연결하고 팀과 함께 선택을 비교하세요. 당신의 다음 행동이 분명해집니다.','Connect market evidence, founder perspective and venture risk. Compare choices with your advisor team and leave with a clear next action.')}),el('div',{class:'p-row p-hero-actions'},button(t('전체 창업 여정 시작하기 →','Start the full journey →'),()=>{track('full_journey_start');window.showPage('m1');},'p-primary'),button(t('지금 고민부터 시작하기','Start with a decision'),()=>document.getElementById('start-with-problem').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})),el('a',{class:'p-button',id:'demo-start',href:world('','demo'),text:t('▶ 3분 데모','▶ Try the 3-minute demo'),onclick:()=>track('demo_start')})),el('p',{class:'p-notice',text:t('설치·가입 없이 체험 · 최종 결정은 Founder에게 있습니다.','No install or signup · The founder makes the final decision.')})),el('div',{class:'p-preview','aria-label':t('의사결정 화면 미리보기 · 예시 데이터','Decision experience preview · illustrative data')},el('div',{class:'p-row p-between p-preview-head'},el('b',{text:'LearnLoop AI'}),el('span',{class:'p-chip',text:t('예시 시나리오','ILLUSTRATIVE SCENARIO')})),el('div',{class:'p-office'},el('div',{class:'p-preview-bubble',text:t('CFO · 선택의 비용과 남은 시간을 함께 봅시다.','CFO · Let’s look at the cost and time to learn.')}),...['CEO','CTO','CFO','Growth','Product'].map((role,i)=>el('div',{class:'p-agent-token'},el('b',{text:['◉','◇','▣','↗','◈'][i]}),role))),el('div',{class:'p-preview-result'},el('div',{class:'p-kicker',text:'ONE DECISION. DIFFERENT FUTURES.'}),el('h3',{text:t('개발자 채용 vs 고객 검증','Developer hire vs customer discovery')}),el('div',{class:'p-preview-metrics'},...[[t('선택','Decision'),'3'],[t('자문 관점','Advisor views'),'6'],[t('다음 행동','Next actions'),'3']].map(([label,value])=>el('div',{},el('strong',{text:value}),el('small',{text:label})))),el('p',{class:'p-notice',text:t('동일 상태와 seed로 비교 · 결과는 모델 가정입니다.','Compare from the same state and seed · modeled outcomes.')}))));
const entries=el('section',{class:'p-wrap p-section'},el('div',{class:'p-section-title'},el('div',{class:'p-kicker',text:'START WHERE YOU ARE'}),el('h2',{text:t('당신의 스타트업에서 지금 무엇이 가장 궁금한가요?','What is your next startup question?')})),el('div',{class:'p-grid'},...[
 ['01',t('전체 창업 여정','The full founder journey'),t('아이디어부터 시장, 나의 의사결정 스타일과 사업 리스크까지 차근차근 점검합니다.','Explore your market, understand your decision style and test venture assumptions.'),t('여정 시작하기 →','Begin the journey →'),()=>{track('full_journey_start');window.showPage('m1');}],
 ['02',t('지금 고민부터 해결','Start with today’s decision'),t('가격, 채용, 투자. 지금 필요한 선택에서 시작하고 필요한 정보만 입력하세요.','Pricing, hiring or funding. Start with your question and add only the context you need.'),t('내 고민 선택하기 →','Choose a question →'),()=>document.getElementById('start-with-problem').scrollIntoView()],
 ['03',t('3분 데모로 체험','A three-minute experience'),t('샘플 AI 교육 스타트업의 CEO가 되어 팀의 토론을 듣고 첫 결정을 실험하세요.','Become CEO of a sample AI education venture. Hear the team and try your first decision.'),t('입력 없이 바로 체험 →','Try without entering data →'),()=>{track('demo_start');location.assign(world('','demo'));}]
 ].map(([num,title,desc,label,fn])=>el('article',{class:'p-card p-entry'},el('span',{class:'p-entry-number',text:num}),el('h3',{text:title}),el('p',{text:desc}),button(label,fn)) )));
const question=el('section',{class:'p-wrap p-section',id:'start-with-problem'},el('div',{class:'p-section-title'},el('h2',{text:t('지금의 질문에서 시작하세요.','Start with your question.')}),el('p',{text:t('모든 단계를 마칠 필요는 없습니다.','You can enter at the step you need.')})),el('div',{class:'p-grid p-problems'},...problems.map(([id,label,destination],i)=>button(label,()=>{track('quick_start');if(destination)window.showPage(destination);else location.assign(world(id,'quick'));}))));
const process=el('section',{class:'p-wrap p-section'},el('div',{class:'p-kicker',text:'A LOOP FOR BETTER DECISIONS'}),el('h2',{text:t('선택하고, 비교하고, 배우고, 행동하세요.','Decide. Compare. Learn. Act.')}),el('div',{class:'p-process'},...['Discover','Understand','Decide','Simulate','Learn','Act'].map(x=>el('span',{text:x}))),el('p',{class:'p-lead',text:'AI advises. The engine simulates. The founder decides.'}));
const research=el('section',{class:'p-section p-research'},el('div',{class:'p-wrap p-stack'},el('div',{class:'p-kicker',text:'METHOD & TRUST'}),el('h2',{text:'Built on research. Honest about its limits.'}),el('div',{class:'p-two'},el('div',{class:'p-card p-stack'},el('h3',{text:t('검증한 것은 활용 경로입니다.','The adoption pathway was studied.')}),el('p',{text:t('n=190 SEM 연구와 15명 사용성 파일럿(SUS 82.2)이 바탕입니다. 창업 생존 예측 정확도나 의사결정 개선 효과를 검증한 결과는 아닙니다.','The foundation includes n=190 SEM research and a 15-participant usability pilot (SUS 82.2). These do not validate venture survival prediction or improved decision quality.')}),el('a',{href:new URL('en/research.html',root).href,text:t('연구·검증 범위 읽기 →','Read the research and limits →')})),el('div',{class:'p-card p-stack'},el('h3',{text:t('결과를 만드는 가정을 공개합니다.','Transparent assumptions, reproducible outcomes.')}),el('p',{text:t('시뮬레이션은 공개된 규칙과 seed로 계산됩니다. 시장 지표는 모델 입력이며, 실시간 검색이나 실제 성공확률로 표현하지 않습니다.','The simulator uses published rules and seeded events. Market indicators are model inputs; they are not live search or real success probabilities.')}),el('a',{href:new URL('module4/ASSUMPTIONS.md',root).href,text:t('모델 가정 살펴보기 →','Inspect model assumptions →')})))));
const footer=el('footer',{class:'p-footer'},el('span',{text:'ASNM · v4.0 · Decision-support pilot'}),el('div',{class:'p-row'},...[[t('소개·로드맵','About & roadmap'),'product/about.html'],[t('개인정보','Privacy'),'privacy.html'],[t('이용 안내','Terms'),'product/terms.html'],[t('문의·피드백','Contact & feedback'),'product/about.html#contact']].map(([label,path])=>el('a',{href:new URL(path,root).href,text:label}))));
home.prepend(hero,entries,question,process,research,footer);track('landing_view');
// Navigation labels describe the user task, while the legacy calculation functions remain intact.
const labels=[t('홈','Home'),t('시장 발견','Discover'),t('창업자 이해','Know yourself'),t('사업 가정 검증','Validate'),t('결정 실험','Simulate'),t('실행 계획','Action plan')];
document.querySelectorAll('.nav-btn').forEach((b,i)=>{if(labels[i])b.textContent=labels[i];});
const nav=el('div',{class:'p-journey-nav','aria-label':t('창업 여정','Founder journey')},...[[t('시장 →','Market →'),'m1'],[t('창업자 →','Founder →'),'m2'],[t('사업 가정 →','Venture assumptions →'),'m3a'],[t('디지털 트윈 ↗','Digital twin ↗'),'m4']].map(([label,id])=>button(label,()=>window.showPage(id))));
document.querySelector('nav')?.after(nav);
const update=()=>{const active=document.querySelector('.page.active');document.body.classList.toggle('asnm-home-active',active===home);nav.hidden=active===home;document.body.classList.toggle('asnm-journey-active',active!==home);nav.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('current',active?.id===['page-m1','page-m2','page-m3a','page-m4'][i]));};
new MutationObserver(update).observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});update();
window.addEventListener('asnm:module3-complete',()=>track('module_complete'));
// Keep original Founder DNA answers/rubric, explain the scope without diagnostic claims.
const founder=document.querySelector('#page-m2 .page-desc');if(founder)founder.textContent=t('10개 질문으로 의사결정 습관을 돌아보세요. 성격 진단이 아닌 자기 점검이며, 유형의 심리측정 타당성은 검증되지 않았습니다.','Reflect on decision habits through ten questions. This is self-reflection, not a personality diagnosis; the typology has not been psychometrically validated.');
const market=document.querySelector('#page-m1 .page-desc');if(market)market.textContent=t('내 아이디어 주변의 고객 문제와 수요 가정을 찾으세요. 기본 카드와 AI 설명은 실시간 시장 증거와 구분해야 합니다.','Explore customer problems and demand assumptions around your idea. Curated cards and AI explanations must be distinguished from live market evidence.');

const founderTitle=document.querySelector('#page-m2 .page-title');if(founderTitle)founderTitle.textContent=t('의사결정 스타일과 주의할 가정','Decision style & assumptions to watch');

const copilotButton=button(t('✧ 결정 도움','✧ Decision help'),()=>{
  let saved=null;try{saved=new StateStore(localStorage).load();}catch{}
  const d=el('dialog',{'aria-label':'ASNM Startup Copilot'},copilotView(saved,lang,document.querySelector('.page.active')?.id,window._founderType||''),button(t('닫기','Close'),()=>{d.close();d.remove();}));d.className='asnm-product';document.body.append(d);d.showModal();
});copilotButton.className='p-copilot-launch';document.body.append(copilotButton);

// Add reflection questions alongside the preserved original questionnaire output.
const reflectionHost=document.getElementById('founder-result');
if(reflectionHost){
 const reflection=el('section',{class:'asnm-product p-card p-stack',style:'text-align:left'},el('h3',{text:t('유형보다, 다음 결정에 사용할 질문','Use the answers to question your next decision')}),el('div',{},el('b',{text:'Strength'}),el('p',{text:t('반복해서 고른 접근을 실제로 잘했던 경험과 연결하세요. 빠른 실행, 분석, 협업 중 무엇이 도움이 되었나요?','Connect recurring choices to an experience where you performed well. Did execution, analysis or collaboration help?')})),el('div',{},el('b',{text:'Watch-outs'}),el('p',{text:t('내 생각을 지지하는 증거만 찾고 있나요? 고객 검증 전에 비용을 크게 늘리려 하나요?','Are you seeking only confirming evidence? Are you scaling spending before validating customers?')})),el('div',{},el('b',{text:'Under pressure'}),el('p',{text:t('시간이나 자금이 부족할 때 기능 개발, 조사, 협상 중 무엇을 먼저 선택할지 점검하세요. 결과는 자기 점검 자료이며 심리 진단이 아닙니다.','When time or cash is scarce, review whether you default to building, researching or negotiating. These questions are self-reflection, not a psychological diagnosis.')})));reflectionHost.append(reflection);
}
