import {renderGuidedDemo} from './guided-demo.js';
import {el,money,fmt,download} from '../module4/ui/dom.js';
import {clone,validateState} from '../module4/state/ASNMState.js';
import {StateStore,SESSION_KEY,createSession,decodeImport} from '../module4/state/StateStore.js';
import {simulateMonth} from '../module4/simulation/SimulationEngine.js';
import {decisions} from '../module4/simulation/DecisionEngine.js';
import {reportMarkdown} from '../module4/ui/report.js';
import {demoState,suggestState,decisionMoment,choicesFor,compareScenarios,actionPlan,journalInsight,morningBrief,discussion,VERSION,tr,roles} from './experience.js';
import {adviseTeam} from './agents.js';
import {copilotView,strategyFromText} from './copilot.js';
import {track} from './telemetry.js';
const params=new URLSearchParams(location.search),lang=params.get('lang')==='en'?'en':'ko',t=(ko,en)=>tr(lang,ko,en),isDemo=params.get('mode')==='demo';
document.documentElement.lang=lang;document.title=t('스타트업 결정 실험 · ASNM','Startup Decision World · ASNM');
const sessionKey=SESSION_KEY+(isDemo?':demo':''),root=new URL('../',import.meta.url),home=new URL(lang==='en'?'en/':'',root).href;
const app=document.getElementById('app');let session=null,source=null,world=null,worldLoading=false,selected=null,team=null,token=0,worldToken=0,busy=false,conflict=false,lastSaved=null,storageOK=true,currentView='decision',speaking=null,dialogueTimer=null,activeRole='CEO',useAI=false;
let babylonLoading=null;
let guidedDemo=isDemo&&params.get('view')!=='workspace',demoStage='intro',demoTurn=0;
const demoScreenKey='asnm:guided-demo:v1';
function rememberDemo(){try{sessionStorage.setItem(demoScreenKey,JSON.stringify({stage:demoStage,turn:demoTurn,month:session.state.simulation.currentMonth}));}catch{}}
function demoMove(stage){demoStage=stage;rememberDemo();render();window.scrollTo(0,0);}
function leaveDemo(view){guidedDemo=false;document.body.classList.remove('p-guided-demo');const u=new URL(location);u.searchParams.set('view','workspace');history.replaceState(null,'',u);currentView=view;if(view==='compare')track('compare_scenario');render();}
async function chooseDemo(option){
 if(busy||conflict)return;selected=option;team=null;busy=true;
 session.productDraft={month:session.state.simulation.currentMonth,reason:'',expectation:'',optionId:option.id};if(!save()){busy=false;return;}
 render();const ticket=++token;
 const response=await adviseTeam(clone(session.state),option,lang,'','');
 if(ticket!==token||conflict){busy=false;return;}team=response;busy=false;demoTurn=0;demoMove('discussion');
}
function showGuidedDemo(){
 document.body.classList.add('p-guided-demo');
 const draft=session.productDraft;
 if(!selected&&draft?.optionId){selected=decisionMoment(session.state).options.find(o=>o.id===draft.optionId)||null;if(selected)team=discussion(session.state,selected,lang,draft.reason);}
 if(['discussion','summary'].includes(demoStage)&&(!selected||!team))demoStage='choice';
 if(['result','action'].includes(demoStage)&&!session.history.length)demoStage='intro';
 renderGuidedDemo({host:content,session,lang,stage:demoStage,turnIndex:demoTurn,selected,team,busy,conflict,home,startOwn:new URL('module4/?lang='+lang+'&mode=quick',root).href,
 onStage:demoMove,onTurn:(index,turn)=>{demoTurn=index;rememberDemo();showBubble(turn.role,turn.text);},onChoose:chooseDemo,onCommit:commit,onWorkspace:leaveDemo,
 onRestart:()=>replaceGuard(()=>{session=createSession(demoState());activeRole='CEO';selected=null;team=null;save();demoTurn=0;demoMove('intro');}),
 mountWorld:(canvas,shell,bubble)=>loadWorld(canvas,shell,bubble)});
}

function ensureBabylon(){
 if(globalThis.BABYLON)return Promise.resolve();
 // Navigation may cancel a world while its runtime is still loading. Share that
 // request: evaluating this bundled runtime twice can write to read-only exports.
 if(!babylonLoading)babylonLoading=new Promise((resolve,reject)=>{const script=el('script',{src:'./vendor/babylon.js',onload:resolve,onerror:()=>{script.remove();babylonLoading=null;reject(new Error('3D runtime unavailable'));}});document.head.append(script);});
 return babylonLoading;
}
const currentProblem=params.get('problem')||'priority';
const store=new StateStore({getItem:key=>localStorage.getItem(key===SESSION_KEY?sessionKey:key),setItem:(key,value)=>localStorage.setItem(key===SESSION_KEY?sessionKey:key,value)});
const btn=(text,fn,props={})=>el('button',{text,onclick:fn,...props});
const link=(text,href)=>el('a',{class:'p-button',text,href});
const status=el('p',{class:'p-status',role:'status','aria-live':'polite',id:'product-status'});
const content=el('main',{class:'p-wrap p-app',id:'product-content'});
const file=el('input',{type:'file',accept:'.json,application/json','aria-label':t('세션 JSON 가져오기','Import session JSON'),style:'display:none',onchange:async()=>{try{const f=file.files[0];if(!f)return;if(f.size>8*1024*1024)throw new Error(t('8MB 이하 파일을 선택하세요.','Select a file under 8 MB.'));const data=decodeImport(await f.text());replaceGuard(()=>{session=data.session||createSession(data.state);activeRole=session.productRole||'CEO';save();enter();});}catch(e){notify(e.message);}finally{file.value='';}}});
const header=el('header',{class:'p-header'},el('a',{class:'p-brand',href:home},el('span',{class:'p-brand-mark',text:'A'}),'ASNM',el('span',{class:'p-small',style:'font-weight:400;margin-left:12px',text:'Decision World'})),el('div',{class:'p-row'},btn(t('새 실험','New venture'),()=>replaceGuard(()=>setup())),btn(t('가져오기','Import'),()=>file.click()),btn(t('저장','Export'),()=>exportSession()),link(lang==='ko'?'EN':'한국어',(()=>{const u=new URL(location);u.searchParams.set('lang',lang==='ko'?'en':'ko');return u.href;})())));
app.append(header,file,el('div',{class:'p-wrap'},status),content,el('footer',{class:'p-footer'},el('span',{text:`ASNM · v${VERSION} · ${t('의사결정 지원 파일럿','Decision-support pilot')}`}),el('div',{class:'p-row'},link(t('모델 가정','Model assumptions'),new URL('module4/ASSUMPTIONS.md',root).href),link(t('기존 몰입형 화면','Classic immersive view'),`./immersive.html?lang=${lang}`),btn(t('피드백','Feedback'),feedback))));
function notify(message){status.textContent=message;}
function save(){
 if(conflict)return false;
 try{const current=localStorage.getItem(sessionKey);if(lastSaved!==null&&current!==lastSaved){conflict=true;notify(t('다른 탭에서 기록이 변경되었습니다. 내보낸 뒤 새로고침하세요.','Another tab changed this session. Export your work and reload.'));return false;}store.save(session);lastSaved=localStorage.getItem(sessionKey);return true;}
 catch{storageOK=false;notify(t('자동 저장이 불가능합니다. JSON 저장으로 기록을 보관하세요.','Autosave is unavailable. Export JSON to retain your work.'));return true;}
}
function exportSession(){if(session){track('report_export');download(JSON.stringify(session,null,2),'ASNM-decision-session.json');}}
function persistDraft(){
 if(!session||currentView!=='decision'||conflict)return;
 const previous=session.productDraft,context=document.getElementById('founder-context'),expectation=document.getElementById('expected-growth');
 if(!context&&!expectation)return;
 const draft={month:session.state.simulation.currentMonth,reason:(context?.value??previous?.reason??'').slice(0,800),expectation:(expectation?.value??previous?.expectation??'').slice(0,30),optionId:selected?.id||previous?.optionId||''};
 if(!draft.reason&&!draft.expectation&&!draft.optionId&&!previous)return;
 if(JSON.stringify(previous)===JSON.stringify(draft))return;
 session.productDraft=draft;
 save();
}
function disposeWorld(){token++;worldToken++;clearTimeout(dialogueTimer);if(world){world.dispose();world=null;}worldLoading=false;}
function replaceGuard(fn){
 if(!session?.history.length){fn();return;}
 const d=el('dialog',{'aria-label':t('새 실험 시작','Start a new experiment')},el('h2',{text:t('현재 기록을 보관하시겠어요?','Keep your current record?')}),el('p',{text:t('새 실험을 시작하면 이 브라우저의 현재 세션이 바뀝니다. 데모와 내 사업 기록은 따로 보관됩니다.','A new experiment replaces this browser session. Demo and personal venture records are stored separately.')}),el('div',{class:'p-row'},btn(t('JSON 저장','Export JSON'),exportSession),btn(t('새 실험 시작','Start new'),()=>{d.close();d.remove();disposeWorld();fn();}),btn(t('취소','Cancel'),()=>{d.close();d.remove();})));document.body.append(d);d.showModal();
}
function setup(initial=null,role='CEO'){
 disposeWorld();selected=null;team=null;content.replaceChildren();
 const fields={},input=(name,label,kind='input',options=[])=>{const node=kind==='select'?el('select',{name,id:'setup-'+name},...options.map(([value,text])=>el('option',{value,text}))):el('input',{name,id:'setup-'+name,type:'text',maxlength:name==='idea'?120:30,required:name==='idea'});fields[name]=node;return el('label',{},label,node);};
 const form=el('form',{class:'p-form',id:'quick-setup',onsubmit:e=>{e.preventDefault();try{const values=Object.fromEntries(Object.entries(fields).map(([k,n])=>[k,n.value]));let s;if(initial){s=clone(initial);s.venture.ventureName=values.idea.trim();if(values.stage!==fields.stage.dataset.original){s.venture.stage=values.stage;s.venture.productProgress={idea:10,interview:20,mvp:46,customer:65,revenue:75,growth:85}[values.stage];}if(values.team!==fields.team.dataset.original)s.venture.teamSize={solo:1,small:3,large:5}[values.team];for(const [key,value] of Object.entries({cash:values.cash,mrr:values.mrr,monthlyBurn:values.burn,retention:values.retention}))if(value!=='')s.venture[key]=Number(value);if(values.demand!=='')s.market.demand=Number(values.demand);s.operations.marketingBudget=Math.min(s.operations.marketingBudget,s.venture.monthlyBurn);s=validateState(s);}else s=suggestState(values);preview(s,values.role);}catch(error){notify(t('입력값을 확인해주세요: ','Please check the inputs: ')+error.message);}}});
 form.append(input('idea',t('사업 아이디어 또는 이름','Your idea or venture name')),el('div',{class:'p-two'},input('stage',t('현재 단계','Current stage'),'select',[['idea',t('아이디어만 있음','Idea')],['interview',t('고객 인터뷰 중','Customer interviews')],['mvp',t('MVP 개발 중','Building MVP')],['customer',t('초기 고객 있음','Early customers')],['revenue',t('매출 발생','Revenue')],['growth',t('성장 단계','Growth')]]),input('team',t('팀','Team'),'select',[['solo',t('혼자','Solo')],['small',t('2–3명','2–3 people')],['large',t('4명 이상','4+ people')]])),el('div',{class:'p-two'},input('funds',t('자금 상황','Funding runway'),'select',[['none',t('거의 없음','Almost none')],['0-3',t('3개월 이하','Up to 3 months')],['3-6',t('3–6개월','3–6 months')],['6-12',t('6–12개월','6–12 months')],['12+',t('12개월 이상','12+ months')]]),input('role',t('내 역할','Your role'),'select',roles.slice(0,5).map(r=>[r,r]))));
 fields.funds.value='6-12';fields.role.value=role;
 const advanced=el('details',{},el('summary',{text:t('상세 수치 설정 · 선택 사항','Advanced settings · optional')}),el('p',{class:'p-notice',text:t(`금액 단위: ${initial?.currency||'KRW'}. 빈 값은 제안값을 사용하며 다음 화면에서 확인합니다.`,`Amounts: ${initial?.currency||'KRW'}. Blank fields use suggested values, shown for review next.`)}),el('div',{class:'p-two'},...[['cash',t('현금','Cash')],['mrr',t('월 반복 매출 (MRR)','Monthly recurring revenue')],['burn',t('월 총비용','Total monthly expenses')],['demand',t('수요 가정 (0–100)','Demand assumption (0–100)')],['retention',t('월 유지율 가정 (%)','Monthly retention assumption (%)')]].map(([key,label])=>input(key,label))));
 for(const k of ['cash','mrr','burn','demand','retention']){fields[k].type='number';fields[k].min='0';fields[k].step='any';if(['demand','retention'].includes(k))fields[k].max='100';}
 if(initial){fields.idea.value=initial.venture.ventureName;const stage=String(initial.venture.stage).toLowerCase();fields.stage.value=['idea','interview','mvp','customer','revenue','growth'].includes(stage)?stage:'mvp';fields.stage.dataset.original=fields.stage.value;fields.team.value=initial.venture.teamSize===1?'solo':initial.venture.teamSize<=3?'small':'large';fields.team.dataset.original=fields.team.value;for(const [key,value] of Object.entries({cash:initial.venture.cash,mrr:initial.venture.mrr,burn:initial.venture.monthlyBurn,demand:initial.market.demand,retention:initial.venture.retention}))fields[key].value=value;const runway=initial.venture.runway;fields.funds.value=runway===null||runway>12?'12+':runway>6?'6-12':runway>3?'3-6':runway>0?'0-3':'none';fields.funds.onchange=()=>{const burn=Number(fields.burn.value),mrr=Number(fields.mrr.value);fields.cash.value=({'none':.5,'0-3':2,'3-6':4.5,'6-12':9,'12+':15}[fields.funds.value])*(burn>mrr?burn-mrr:burn);};}
 form.append(advanced,el('button',{type:'submit',class:'p-primary',id:'review-start',text:t('제안된 시작 상태 확인 →','Review suggested starting state →')}));
 content.append(el('div',{class:'p-kicker',text:'YOUR VENTURE / MINIMUM CONTEXT'}),el('h1',{class:'p-app-title',text:initial?t('앞선 결과로 실험을 시작하세요.','Start from your previous results.'):t('네 가지 정보로 시작하세요.','Start with four simple details.')}),el('p',{class:'p-lead',text:t('시작 상태는 수정 가능한 시나리오입니다. 전문 재무 지식이 없어도 됩니다.','Your starting state is an editable scenario. You do not need financial expertise.')}),el('section',{class:'p-card',style:'max-width:700px;margin-top:25px'},form));
}
function metrics(state){const v=state.venture;return el('section',{class:'p-metrics','aria-label':t('현재 회사 상태','Current venture state')},...[[t('현금','Cash'),money(v.cash,state.currency,lang)],[t('남은 자금 기간','Runway'),v.runway===null?t('순현금소진 없음','No net burn'):`${fmt(v.runway)} ${t('개월','mo')}`],['MRR',money(v.mrr,state.currency,lang)],[t('수요 가정','Demand assumption'),`${fmt(state.market.demand)}/100`]].map(([label,value])=>el('div',{class:'p-metric'},el('small',{text:label}),el('b',{text:value}))));}
function preview(state,role){
 content.replaceChildren(el('div',{class:'p-kicker',text:'REVIEW YOUR ASSUMPTIONS'}),el('h1',{class:'p-app-title',text:state.venture.ventureName}),metrics(state),el('section',{class:'p-card p-stack',style:'margin-top:24px'},el('h2',{text:t('이 시작 가정으로 실험할까요?','Use these starting assumptions?')}),el('p',{text:t('수치와 효과는 가정이며 실제 사업 실적이 아닙니다. 초기 수요·유지율·CAC에는 예시값이 사용되므로 고객 증거로 교체하세요.','Values and effects are assumptions, not actual business results. Initial demand, retention and CAC can include example values; replace them with customer evidence.')}),el('p',{text:`${t('팀','Team')}: ${state.venture.teamSize} · ${t('제품','Product')}: ${state.venture.productProgress}/100 · CAC: ${money(state.venture.cac,state.currency,lang)} · ${t('유지율','Retention')}: ${state.venture.retention}% · ${t('역할','Role')}: ${role}`}),el('details',{},el('summary',{text:t('데이터 출처·나머지 가정','Provenance & remaining assumptions')}),el('pre',{style:'white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px',text:JSON.stringify({market:state.market,operations:state.operations,founder:state.founder,provenance:state.provenance},null,2)})),el('div',{class:'p-row'},btn(t('수정하기','Edit assumptions'),()=>setup(state,role)),btn(t('결정 실험 시작 →','Enter Decision World →'),()=>{session=createSession(state);activeRole=role;session.productRole=role;session.experience={role:role==='CFO'?'finance':role==='CTO'?'product':role.toLowerCase()};lastSaved=storageOK?localStorage.getItem(sessionKey):null;save();enter();},{class:'p-primary',id:'enter-decision-world'}))));
}
function enter(){disposeWorld();currentView='decision';selected=null;team=null;busy=false;
 if(guidedDemo){demoStage=session.history.length?'result':'intro';try{const saved=JSON.parse(sessionStorage.getItem(demoScreenKey));if(saved?.month===session.state.simulation.currentMonth&&['intro','choice','discussion','summary','result','action'].includes(saved.stage)){demoStage=saved.stage;demoTurn=Number.isInteger(saved.turn)?saved.turn:0;}}catch{}}
 track('digital_twin_enter');render();}
function render(){
 if(!session)return;
 disposeWorld();content.replaceChildren();
 if(guidedDemo){showGuidedDemo();return;}
 const s=session.state;
 const roleSelect=el('select',{id:'player-role','aria-label':t('사용자 역할','Player role'),onchange:()=>{activeRole=roleSelect.value;document.querySelector('#product-content h1').textContent=`${t('좋은 아침입니다,','Good morning,')} ${activeRole}.`;session.productRole=activeRole;session.experience={...session.experience,role:activeRole==='CFO'?'finance':activeRole==='CTO'?'product':activeRole.toLowerCase()};save();world?.setRole(activeRole);}},...roles.slice(0,5).map(r=>el('option',{value:r,text:r})));roleSelect.value=activeRole;
 const tabs=el('nav',{class:'p-tabbar',role:'tablist','aria-label':t('결정 도구','Decision tools')},...[[t('결정 실험','Decision'),'decision'],[t('다른 선택이라면?','What if?'),'compare'],[t('결정 기록','Journal'),'journal'],[t('실행 계획','Action plan'),'report']].map(([label,id])=>btn(label,()=>{persistDraft();currentView=id;if(id==='compare')track('compare_scenario');if(id==='report')track('report_view');render();},{role:'tab','aria-selected':currentView===id,id:'view-'+id})));
 content.append(el('div',{class:'p-row p-between'},el('div',{},el('div',{class:'p-kicker',text:isDemo?'ILLUSTRATIVE DEMO / AI EDUCATION STARTUP':'YOUR STARTUP / DECISION WORLD'}),el('h1',{class:'p-app-title',text:`${t('좋은 아침입니다,','Good morning,')} ${activeRole}.`}),el('p',{text:`${s.venture.ventureName} · ${t('실험','Round')} ${s.simulation.currentMonth+1}`})),el('label',{style:'width:160px'},t('내 역할','Your role'),roleSelect)),metrics(s),tabs);
 const plan=actionPlan(session,lang);content.append(el('p',{class:'p-notice',text:`${t('현재 가장 큰 위험','Biggest current risk')}: ${plan.risk} · ${t('가정 기반 시나리오입니다. 실제 성공확률이나 예측이 아닙니다.','Assumption-based scenario, not a success probability or forecast.')}`}));
 if(currentView==='compare'){renderCompare();return;}if(currentView==='journal'){renderJournal();return;}if(currentView==='report'){renderReport();return;}
 const draft=session.productDraft;
 if(!selected&&draft?.month===s.simulation.currentMonth&&draft.optionId){const option=draft.optionId==='custom'?strategyFromText(draft.reason,s,lang):decisionMoment(s,currentProblem).options.find(o=>o.id===draft.optionId);if(option){selected=option;team=discussion(s,option,lang,draft.reason);}}
 const left=el('div',{class:'p-stack'}),right=el('aside',{class:'p-card p-stack',id:'decision-panel'});
 const canvas=el('canvas',{id:'living-world',tabindex:'0','aria-label':t('3D 회사. WASD 또는 화살표로 이동하고 아래 역할 버튼으로 방을 방문하세요.','3D company. Use WASD/arrows or the role buttons to visit rooms.')});
 const bubble=el('div',{class:'p-bubble',id:'agent-bubble',role:'status','aria-live':'polite'},el('strong',{text:'CFO'}),el('span',{text:t(`현재 Runway는 ${s.venture.runway??'∞'}개월입니다. 오늘 가장 중요한 결정 하나를 실험해봅시다.`,`Runway is ${s.venture.runway??'∞'} months. Let’s test one important decision today.`)}));
 const shell=el('section',{class:'p-world'},el('div',{class:'p-world-bar'},el('span',{text:t('살아 있는 스타트업 · 시나리오','LIVING STARTUP · SCENARIO')}),el('div',{class:'p-row'},btn(t('전체','Overview'),()=>world?.setView('overview')),btn(t('3인칭','Third person'),()=>world?.setView('third')),btn(t('1인칭','First person'),()=>world?.setView('first')))),canvas,bubble);
 const roomMap={CEO:'ceo',CTO:'product',CFO:'finance',Growth:'market',Product:'product',Customer:'customer',Investor:'investor'};
 left.append(shell,el('nav',{class:'p-row p-room-nav','aria-label':t('역할의 방 방문','Visit role rooms')},...roles.map(r=>btn(r,()=>{world?.goToRoom(roomMap[r]);showBubble(r,t(`${r} 관점에서 이번 선택을 검토합니다. 팀 토론에서 다른 의견도 들어보세요.`,`Review this choice from ${r}’s viewpoint. Hear other perspectives in the team discussion.`));}))),el('p',{class:'p-notice',text:t('화면의 자문 캐릭터는 실제 팀 인원과 별개입니다. 고객 수는 이 엔진에서 추적하지 않습니다.','Advisor characters are separate from actual team size. Customer count is not tracked by this engine.')}));
 content.append(el('div',{class:'p-dashboard'},left,right));
 const brief=morningBrief(session,lang);
 left.append(el('details',{class:'p-card p-brief',id:'morning-brief'},el('summary',{text:t('오늘의 팀 브리핑 · 규칙 기반','Today’s team brief · rule-based')}),...brief.map(turn=>el('p',{class:'p-small','data-brief-role':turn.role},el('b',{text:`${turn.role} → ${turn.replyTo}: `}),turn.text))),copilotView(session,lang));renderDecision(right);loadWorld(canvas,shell,bubble);
 playDialogue(team?.turns||brief);
 if(session.history.length)renderOutcome(left,session.history.at(-1));
}
async function loadWorld(canvas,shell,bubble){
 canvas.addEventListener('webglcontextlost',()=>{
  if(!canvas.isConnected)return;
  canvas.hidden=true;bubble.hidden=true;
  if(!shell.querySelector('#webgl-fallback'))shell.append(el('div',{class:'p-world-fallback',id:'webgl-fallback'},el('h3',{text:t('2D 모드로 계속할 수 있습니다.','Continue in 2D mode.')}),el('p',{style:'color:#dbeadd',text:t('3D 그래픽 연결이 끊겼습니다. 결정, 토론, 비교와 기록은 그대로 사용할 수 있습니다.','The 3D graphics context was lost. Decisions, discussion, comparison and records remain available.')})));
 },{once:true});
 if(worldLoading)return;worldLoading=true;const ticket=worldToken;
 try{
  await ensureBabylon();
  if(ticket!==worldToken)return;
  const {createWorld}=await import('../module4/world/createWorld.js');if(ticket!==worldToken)return;
  world=createWorld(canvas,room=>world?.goToRoom(room),()=>{},{productExperience:true});world.update(session.state,session.history.at(-1));world.setRole(activeRole);if(team)world.meeting(true);canvas.dataset.ready='true';
  world.scene.onAfterRenderObservable.add(()=>{if(!speaking)return;const actor=world?.avatars.actors.find(a=>(a.role===speaking)||(a.role===undefined&&a.roomId===({CTO:'product',Product:'product',CFO:'finance',Growth:'market',Customer:'customer',Investor:'investor',CEO:'ceo'}[speaking])));if(!actor)return;const B=globalThis.BABYLON,pos=actor.root.position.add(new B.Vector3(0,3.4,0)),engine=world.scene.getEngine(),p=B.Vector3.Project(pos,B.Matrix.Identity(),world.scene.getTransformMatrix(),world.camera.viewport.toGlobal(engine.getRenderWidth(),engine.getRenderHeight()));bubble.style.left=Math.max(8,Math.min(canvas.clientWidth-bubble.offsetWidth-8,p.x*canvas.clientWidth/engine.getRenderWidth()-bubble.offsetWidth/2))+'px';bubble.style.top=Math.max(canvas.offsetTop+8,Math.min(canvas.offsetTop+canvas.clientHeight-bubble.offsetHeight-12,p.y*canvas.clientHeight/engine.getRenderHeight()+canvas.offsetTop))+'px';});
 }catch{if(ticket!==worldToken)return;canvas.hidden=true;bubble.hidden=true;shell.append(el('div',{class:'p-world-fallback',id:'webgl-fallback'},el('h3',{text:t('팀과 함께 결정하는 2D 모드','Your decision team in 2D')}),el('p',{style:'color:#dbeadd',text:t('3D를 사용할 수 없는 환경입니다. 아래 팀 토론·선택·비교·실행 계획을 모두 사용할 수 있습니다.','3D is unavailable here. Team discussion, decisions, comparison and action plans remain available.')}),el('div',{class:'p-row'},...roles.map(r=>el('span',{class:'p-chip',text:r})))));
 }finally{if(ticket===worldToken)worldLoading=false;}
}
function playDialogue(turns){clearTimeout(dialogueTimer);let index=0;const ticket=token;const play=()=>{if(ticket!==token||index>=turns.length||!document.getElementById('agent-bubble'))return;const turn=turns[index++];showBubble(turn.role,turn.text);dialogueTimer=setTimeout(play,matchMedia('(prefers-reduced-motion: reduce)').matches?500:3500);};play();}
function showBubble(role,text){speaking=role;const b=document.getElementById('agent-bubble');if(!b)return;b.replaceChildren(el('strong',{text:role==='Founder'?activeRole:role}),el('span',{text}));world?.conversation(({CTO:'product',Product:'product',CFO:'finance',Growth:'market',Customer:'customer',Investor:'investor',Founder:({CEO:'ceo',CFO:'finance',CTO:'product',Growth:'market',Product:'product'})[activeRole],CEO:'ceo'})[role]||'ceo','talk');}
function renderDecision(host){
 const s=session.state,moment=decisionMoment(s,currentProblem),ended=s.venture.cash<=0||s.simulation.currentMonth>=60;
 host.replaceChildren(el('div',{class:'p-kicker',text:'TODAY’S DECISION'}),el('h2',{text:t(moment.ko,moment.en)}),el('p',{class:'p-small',text:t('선택을 검토하고 팀의 의견을 들은 뒤, 최종 결정하세요.','Review a choice, hear the team, then make the final decision.')}));
 if(ended){host.append(el('p',{text:t('시나리오가 종료되었습니다. 기록과 실행 계획을 확인하거나 새 실험을 시작하세요.','The scenario has ended. Review the journal and action plan or start a new experiment.')}));return;}
 const aiToggle=el('input',{type:'checkbox',id:'enable-ai',style:'width:18px;min-height:18px',onchange:()=>{useAI=aiToggle.checked;}});aiToggle.checked=useAI;
 host.append(el('label',{style:'display:flex;align-items:flex-start;font-size:.76rem'},aiToggle,t('AI 팀 자문 사용 · 현재 사업 상태와 문장을 AI 프록시에 전송합니다.','Use AI team advice · sends current venture state and your message to the AI proxy.')));
 host.append(el('div',{class:'p-options'},...moment.options.map(o=>btn('',()=>reviewOption(o),{class:'p-option'+(selected?.id===o.id?' selected':''),'data-option':o.id,'aria-pressed':selected?.id===o.id,disabled:busy||conflict})).map((b,i)=>{b.append(el('b',{text:t(moment.options[i].ko,moment.options[i].en)}),el('small',{text:t(moment.options[i].whyKo,moment.options[i].whyEn)}));return b;})));
 const context=el('textarea',{id:'founder-context',maxlength:'800',placeholder:t('짧은 전략이나 이유를 팀에 말해보세요. 예: 채용을 미루고 고객을 만나고 싶어요.','Tell the team a short strategy or reason. Example: hold hiring and interview customers.')});
 const expected=el('input',{id:'expected-growth',type:'number',min:'-100',max:'1000',step:'any',placeholder:t('선택 사항','Optional')});
 const draft=session.productDraft;if(draft?.month===s.simulation.currentMonth){context.value=draft.reason;expected.value=draft.expectation;}
 context.oninput=persistDraft;expected.oninput=persistDraft;
 host.append(el('label',{},t('내 생각 · 선택 사항','Your thinking · optional'),context),el('div',{class:'p-row'},btn(t('팀에 전달','Tell the team'),()=>{const text=context.value.trim();if(!text)return;showBubble('Founder',text);const proposed=strategyFromText(text,session.state,lang);if(proposed)reviewOption(proposed,text);else if(selected)reviewOption(selected,text);else notify(t('의견을 기록했습니다. 위의 선택지를 골라 실행 규칙을 확인하세요.','Your thinking is captured. Select a choice above to review its executable rule.'));}),btn(t('🎙 말하기','🎙 Speak'),()=>voice(context),{id:'speak-button'})),el('label',{},t('내 예상 MRR 성장률 (%) · 선택 사항','Expected MRR growth (%) · optional'),expected));
 if(team&&selected)renderTeam(host);
 else host.append(el('p',{class:'p-notice',text:busy?t('팀이 선택을 검토하고 있습니다…','The team is reviewing your choice…'):t('최종 결정은 Founder에게 있습니다.','The founder makes the final decision.')}));
}
async function reviewOption(option,user){
 if(busy||conflict)return;selected=option;team=null;busy=true;
 persistDraft();
 const context=document.getElementById('founder-context')?.value||'',expect=document.getElementById('expected-growth')?.value||'';
 const host=document.getElementById('decision-panel');const ticket=++token;renderDecision(host);document.getElementById('founder-context').value=user??context;document.getElementById('expected-growth').value=expect;
 const state=clone(session.state);world?.meeting(true);
 const response=await adviseTeam(state,option,lang,user??context,useAI?globalThis.ASNM_CONFIG?.aiProxyUrl:'',globalThis.fetch,{recentDecisions:session.history.slice(-3).map(r=>({month:r.month,choices:r.decisions.map(d=>({category:d.category,action:d.action})),reason:r.founderReason})),founderOrientation:session.state.founder.decisionOrientation});
 if(ticket!==token||conflict){busy=false;return;}team=response;busy=false;
 const savedContext=document.getElementById('founder-context')?.value||'',savedExpectation=document.getElementById('expected-growth')?.value||'';
 renderDecision(host);document.getElementById('founder-context').value=savedContext;document.getElementById('expected-growth').value=savedExpectation;
 persistDraft();playDialogue(team.turns);
}
function renderTeam(host){
 host.append(el('div',{class:'p-row p-between'},el('h3',{text:t('팀 토론','Team discussion')}),el('span',{class:'p-chip',id:'advisor-mode',text:team.source==='llm'?t('AI 팀 자문','AI team advice'):useAI?t('규칙 기반 자문 · AI 응답 불가','Rule-based · AI unavailable'):t('규칙 기반 팀 자문','Rule-based team advice')})),el('section',{class:'p-discussion',id:'team-discussion','aria-label':t('역할별 토론 기록','Role discussion log')},...team.turns.map(turn=>el('article',{class:'p-turn'},el('span',{class:'p-avatar',text:turn.role.slice(0,2)}),el('div',{},el('small',{text:`${turn.role} → ${turn.replyTo}`}),el('p',{text:turn.text}))))),el('div',{class:'p-summary'},...Object.entries(team.summary).map(([key,text])=>el('div',{},el('b',{text:({agreement:t('동의','Agreement'),disagreement:t('의견 차이','Disagreement'),tradeoff:t('핵심 절충','Trade-off'),question:t('Founder의 질문','Founder question')})[key]+': '}),text))),el('details',{},el('summary',{text:t('이 선택의 실행 규칙 보기','Review the executable choices')}),el('p',{class:'p-notice',text:t('언급하지 않은 항목은 아래 기본값으로 계산됩니다.','Other categories use these explicit default choices.')}),el('ul',{},...Object.entries(choicesFor(session.state,selected)).map(([category,action])=>el('li',{class:'p-small',text:`${category}: ${decisions[category].find(d=>d[0]===action)[lang==='ko'?1:2]}`})))),btn(t(`「${selected.ko}」 결정 · 한 달 실험 →`,`Commit “${selected.en}” · simulate one month →`),commit,{class:'p-primary',id:'commit-decision',disabled:conflict}));
}
function commit(){
 if(busy||conflict||!team||!selected)return;
 const raw=document.getElementById('expected-growth')?.value??session.productDraft?.expectation??'',expected=raw===''?null:Number(raw);if(expected!==null&&(!Number.isFinite(expected)||expected<-100||expected>1000)){notify(t('예상 성장률은 -100~1000 사이로 입력하세요.','Enter expected growth between -100 and 1000.'));return;}
 const reason=document.getElementById('founder-context')?.value||session.productDraft?.reason||'';
 try{const before=session.state,result=simulateMonth(before,choicesFor(before,selected),reason,new Date().toISOString());const next=clone(session);delete next.productDraft;next.state=result.state;next.history.push(result.log);next.decisionJournal??=[];next.decisionJournal.push({logId:result.log.id,option:t(selected.ko,selected.en),reason,expectedGrowth:expected,modeledGrowth:before.venture.mrr>0?(result.state.venture.mrr/before.venture.mrr-1)*100:null});const old=session;session=next;if(!save()){session=old;return;}if(session.history.length===1)track('first_decision');track('simulation_complete');selected=null;team=null;if(guidedDemo){demoStage='result';rememberDemo();}render();notify(t('모델 결과와 다음 행동이 준비되었습니다. 아래에서 변화와 실행 계획을 확인하세요.','Modeled outcomes and next actions are ready. Review the changes and action plan below.'));document.getElementById('decision-outcome')?.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}catch(e){notify(e.message);}
}
function renderOutcome(host,log){
 const s=session.state,plan=actionPlan(session,lang),before=log.stateBefore,after=log.stateAfter;
 const items=[['runway',t('Runway (개월)','Runway (months)'),before.venture.runway,after.venture.runway],['mrr','MRR',before.venture.mrr,after.venture.mrr],['product',t('제품 완성도','Product readiness'),before.venture.productProgress,after.venture.productProgress],['demand',t('수요 가정','Demand assumption'),before.market.demand,after.market.demand],['retention',t('유지율 (%)','Retention (%)'),before.venture.retention,after.venture.retention],['team',t('팀 규모','Team size'),before.venture.teamSize,after.venture.teamSize]];
 host.append(el('section',{class:'p-card p-stack p-fade',id:'decision-outcome'},el('div',{class:'p-kicker',text:`MODELED OUTCOME / MONTH ${log.month}`}),el('h2',{text:t('당신의 선택으로 무엇이 달라졌나요?','What changed after your decision?')}),el('p',{class:'p-small',text:`${t('이번 달 이벤트','This month’s event')}: ${t(log.event.ko,log.event.en)}`}),el('div',{class:'p-result-grid'},...items.map(([id,label,a,b])=>el('article',{class:'p-change','data-metric':id},el('span',{text:label}),el('b',{'data-animate':id,'data-before':a??'unbounded','data-after':b??'unbounded',text:`${id==='mrr'?money(a,s.currency,lang):fmt(a)} → ${id==='mrr'?money(b,s.currency,lang):fmt(b)}`}),el('span',{text:b===a?'—':(b>a?'↑ ':'↓ ')+(a===null||b===null?'':fmt(Math.abs(b-a)))})))),el('p',{class:'p-notice',text:t('변화에는 선택과 월별 이벤트가 함께 반영됩니다. 개별 선택의 인과 효과나 실제 결과가 아닙니다.','Changes include all choices and monthly events. They are not isolated causal effects or observed results.')}),el('h3',{text:t('다음 7일, 해야 할 3가지','Your next three actions for seven days')}),el('ol',{},...plan.week.map(x=>el('li',{text:x}))),el('div',{class:'p-row'},btn(t('다른 선택이었다면?','What if I chose differently?'),()=>{currentView='compare';track('compare_scenario');render();}),btn(t('실행 계획 보기','Open action plan'),()=>{currentView='report';track('report_view');render();},{class:'p-primary'}))));
 if(!matchMedia('(prefers-reduced-motion: reduce)').matches){
   const start=performance.now(),nodes=[...host.querySelectorAll('[data-animate]')];
   const frame=now=>{const progress=Math.min(1,(now-start)/650);for(const n of nodes){const a=Number(n.dataset.before),b=Number(n.dataset.after);if(!Number.isFinite(a)||!Number.isFinite(b))continue;const value=a+(b-a)*progress;n.textContent=n.dataset.animate==='mrr'?`${money(a,s.currency,lang)} → ${money(value,s.currency,lang)}`:`${fmt(a)} → ${fmt(value)}`;}if(progress<1&&nodes[0]?.isConnected)requestAnimationFrame(frame);};requestAnimationFrame(frame);
 }
}
function renderCompare(){
 const initial=session.history.length?(()=>{const s=clone(session.state),row=session.history.at(-1);s.venture=clone(row.stateBefore.venture);s.market=clone(row.stateBefore.market);s.operations=clone(row.stateBefore.operations);s.simulation.currentMonth=row.month-1;return validateState(s);})():session.state;
 const options=decisionMoment(initial,currentProblem).options;
 const a=el('select',{id:'scenario-a','aria-label':'Scenario A'},...options.map(o=>el('option',{value:o.id,text:t(o.ko,o.en)}))),b=el('select',{id:'scenario-b','aria-label':'Scenario B'},...options.map(o=>el('option',{value:o.id,text:t(o.ko,o.en)})));b.selectedIndex=Math.min(1,options.length-1);
 const table=el('div',{class:'p-table-wrap',id:'comparison-results'});
 const recalc=()=>{try{const result=compareScenarios(initial,options.find(o=>o.id===a.value),options.find(o=>o.id===b.value));const fields=[['runway',t('Runway · 개월','Runway · months'),s=>s.venture.runway],['mrr','MRR',s=>s.venture.mrr],['product',t('제품 완성도','Product readiness'),s=>s.venture.productProgress],['retention',t('고객 유지율 (%)','Retention (%)'),s=>s.venture.retention],['demand',t('수요 가정','Demand assumption'),s=>s.market.demand],['uncertainty',t('불확실성','Uncertainty'),s=>s.market.uncertainty],['equity',t('창업자 지분 (%)','Founder ownership (%)'),s=>s.operations.founderEquity],['acquired',t('이번 달 획득 고객 · 모델','Acquired customers · modeled'),(s,r)=>r.log.operating.acquiredCustomers]];
 table.replaceChildren(el('table',{},el('caption',{style:'text-align:left;padding:10px 0',text:t(`같은 상태 · Seed ${initial.simulation.seed} · 월 ${initial.simulation.currentMonth+1}`,`Same state · seed ${initial.simulation.seed} · month ${initial.simulation.currentMonth+1}`)}),el('thead',{},el('tr',{},el('th',{scope:'col',text:t('지표','Metric')}),...result.map(r=>el('th',{scope:'col',text:t(r.option.ko,r.option.en)})))),el('tbody',{},...fields.map(([id,label,read])=>{const vals=result.map(r=>read(r.state,r));return el('tr',{'data-compare':id},el('th',{scope:'row',text:label}),...vals.map(n=>el('td',{},id==='mrr'?money(n,initial.currency,lang):fmt(n),el('span',{class:'p-bar',style:`width:${n===null?100:Math.max(2,n/Math.max(...vals.filter(v=>v!==null),1)*100)}%`}))));}))),el('p',{class:'p-notice',text:t('동일 seed라도 투자·선택별 조건이 달라 적용되는 이벤트가 다를 수 있습니다. 고객 획득은 유료 전환 규칙의 모델 값이며, 누적 고객 수를 추적하지 않습니다.','With the same seed, conditional event effects can differ by choices. Acquired customers are modeled conversions; the engine does not track a cumulative customer count.')}));}catch(e){table.replaceChildren(el('p',{class:'p-error',text:e.message}));}};
 a.addEventListener('change',recalc);b.addEventListener('change',recalc);
 content.append(el('section',{class:'p-card p-stack'},el('h2',{text:t('같은 출발점, 다른 선택.','Same starting point. Different decisions.')}),el('p',{text:t('가장 최근 결정 직전 상태를 복제하여 비교합니다. 이 실험은 현재 기록을 바꾸지 않습니다.','Compare copies of the state before your latest decision. This experiment does not change your committed history.')}),el('div',{class:'p-two'},el('label',{},'Scenario A',a),el('label',{},'Scenario B',b)),table));recalc();
}
function renderJournal(){
 content.append(el('section',{class:'p-card p-stack'},el('h2',{text:t('당신의 선택이 학습 기록이 됩니다.','Your decisions become a learning record.')}),el('p',{text:journalInsight(session,lang)}),...session.history.map(row=>{const j=session.decisionJournal?.find(x=>x.logId===row.id);return el('article',{class:'p-report-section'},el('h3',{text:`${t('월','Month')} ${row.month} · ${j?.option||row.decisions.map(d=>d.action).join(' / ')}`}),el('p',{text:`${t('이유','Reason')}: ${j?.reason||row.founderReason||t('입력하지 않음','Not entered')}`}),el('p',{text:`${t('예상 성장률','Expected MRR growth')}: ${j?.expectedGrowth??'—'}% · ${t('모델 결과','Modeled growth')}: ${j?.modeledGrowth==null?'—':fmt(j.modeledGrowth)}%`}),el('p',{text:`${t('이벤트','Event')}: ${t(row.event.ko,row.event.en)}`}),el('label',{},t('배운 점 · 다음 가정','Learning · next assumption'),el('textarea',{maxlength:'2000','data-reflection':row.id,text:session.reflections?.[`${row.id}-review-${row.month}`]||'',onchange:e=>{session.reflections[`${row.id}-review-${row.month}`]=e.target.value;save();}})));}),session.history.length?null:el('p',{text:t('첫 결정을 마치면 이곳에 기록됩니다.','Complete your first decision to begin the journal.')})));
}
function planMarkdown(){const p=actionPlan(session,lang);return reportMarkdown(session)+'\n\n## Biggest risk\n'+p.risk+'\n\n## Biggest assumptions\n'+p.assumptions.map(x=>'- '+x).join('\n')+'\n\n## Founder decision patterns\n'+journalInsight(session,lang)+'\n\n## Next three actions / 7 days\n'+p.week.map((x,i)=>`${i+1}. ${x}`).join('\n')+'\n\n## 30-day experiment\n'+p.month+'\n\n## What to measure\n'+p.measure+'\n\n## Next decision to revisit\n'+p.revisit;}
function renderReport(){
 const p=actionPlan(session,lang),s=session.state,last=session.history.at(-1);
 const sections=[['01',t('현재 사업 상태','Current venture state'),`${s.venture.ventureName} · ${t('월','Month')} ${s.simulation.currentMonth} · Cash ${money(s.venture.cash,s.currency,lang)} · Runway ${fmt(s.venture.runway)}`],['02',t('가장 중요한 가정','Biggest assumptions'),p.assumptions.join(' ')],['03',t('주요 위험','Top risks'),p.risk],['04',t('실험한 결정','Decisions tested'),session.history.map(r=>`${r.month}: ${session.decisionJournal?.find(j=>j.logId===r.id)?.option||r.decisions.map(d=>d.action).join(', ')}`).join(' / ')||t('아직 없음','None yet')],['05',t('달라진 것','What changed'),last?`MRR ${money(last.stateBefore.venture.mrr,s.currency,lang)} → ${money(last.stateAfter.venture.mrr,s.currency,lang)}; ${t('수요','Demand')} ${last.stateBefore.market.demand} → ${last.stateAfter.market.demand}`:t('첫 결정 후 비교합니다.','Compare after your first decision.')],['06',t('창업자 의사결정 기록','Founder decision patterns'),journalInsight(session,lang)],['07',t('다음 7일 동안 해야 할 3가지','Three actions for the next seven days'),p.week],['08',t('30일 실험 계획','30-day experiment plan'),p.month],['09',t('무엇을 측정할까요?','What to measure'),p.measure],['10',t('다시 검토할 결정','Next decision to revisit'),p.revisit]];
 content.append(el('section',{class:'p-card p-stack',id:'action-report'},el('div',{class:'p-row p-between'},el('h2',{text:t('내일 무엇을 할지, 분명하게.','A clear plan for tomorrow.')}),el('div',{class:'p-row'},btn(t('실행 계획 다운로드','Download action plan'),()=>{track('report_export');download(planMarkdown(),'ASNM-action-plan.md','text/markdown');},{id:'export-plan'}),btn(t('인쇄 / PDF','Print / PDF'),()=>print()))),...sections.map(([n,title,body])=>el('article',{class:'p-report-section'},el('h3',{text:`${n}. ${title}`}),Array.isArray(body)?el('ol',{},...body.map(x=>el('li',{text:x}))):el('p',{text:body}))),el('details',{},el('summary',{text:t('데이터 출처와 모델 한계','Data provenance and limits')}),el('p',{class:'p-notice',text:(s.provenance?.notes||[]).join(' ')}),el('p',{text:t('창업자 유형은 자기 점검 참고 정보입니다. 생존확률·심리 진단·투자 성과를 검증한 도구가 아닙니다.','Founder orientation is a self-reflection input. This tool does not validate survival probabilities, psychological diagnoses or investment performance.')})),s.provenance?.module3?link(t('기존 종합 보고서','Original comprehensive report'),home+'?view=module3-report#report='+encodeURIComponent(JSON.stringify(s.provenance.module3))):null));
}
function voice(input){const API=globalThis.SpeechRecognition||globalThis.webkitSpeechRecognition;if(!API){notify(t('이 브라우저는 음성 입력을 지원하지 않습니다. 위에 짧게 입력해주세요.','Speech recognition is unavailable. Type your thinking above.'));input.focus();return;}const recognition=new API();recognition.lang=lang==='ko'?'ko-KR':'en-US';recognition.onresult=e=>{input.value=(input.value+' '+e.results[0][0].transcript).trim().slice(0,800);persistDraft();showBubble('Founder',input.value);notify(t('말을 텍스트로 옮겼습니다. 팀에 전달하거나 선택을 검토하세요.','Speech was transcribed. Send it to the team or review a choice.'));};recognition.onerror=()=>notify(t('음성을 인식하지 못했습니다. 텍스트로 입력할 수 있습니다.','Speech was not recognized. Text input remains available.'));try{recognition.start();notify(t('듣고 있습니다…','Listening…'));}catch{notify(t('음성 입력을 시작할 수 없습니다. 텍스트로 입력해주세요.','Speech input could not start. Please type instead.'));}}
function feedback(){
 const d=el('dialog',{'aria-label':t('사용 경험 피드백','Experience feedback')}),form=el('form',{class:'p-form',onsubmit:e=>{e.preventDefault();track('feedback_submit');const answers=Object.fromEntries(new FormData(form));download(JSON.stringify({version:VERSION,answers},null,2),'ASNM-feedback.json');notify(t('피드백을 파일로 저장했습니다. 소개 페이지의 GitHub 피드백 링크로 직접 공유할 수 있습니다.','Feedback saved as a file. You can share it using the GitHub feedback link on the About page.'));d.close();d.remove();}});
 form.append(el('h2',{text:t('잠깐, 경험은 어떠셨나요?','How was your experience?')}),...['ASNM을 어떤 서비스로 이해했나요?','가장 도움이 된 기능은?','가장 어려웠던 부분은?','다시 사용할 것 같나요?','누구에게 유용할까요?'].map((q,i)=>el('label',{},t(q,['How do you understand ASNM?','Most useful feature?','Hardest part?','Would you use it again?','Who would benefit?'][i]),el('input',{name:'q'+i,maxlength:'300'}))),el('p',{class:'p-notice',text:t('응답은 서버로 전송되지 않으며 내보내기 파일에만 포함됩니다.','Responses are not sent to a server; they appear only in your exported file.')}),el('div',{class:'p-row'},el('button',{type:'submit',class:'p-primary',text:t('피드백 저장','Save feedback')}),btn(t('닫기','Close'),()=>{d.close();d.remove();},{type:'button'})));d.append(form);document.body.append(d);d.showModal();
}
window.addEventListener('pagehide',disposeWorld);
window.addEventListener('storage',e=>{if(e.key===sessionKey||e.key===null){conflict=true;token++;busy=false;notify(t('다른 탭이 기록을 변경했습니다. 내보낸 뒤 새로고침하세요.','Another tab changed the session. Export and reload.'));if(session)render();}});
try{lastSaved=localStorage.getItem(sessionKey);session=store.load();source=store.readSource();}catch{storageOK=false;notify(t('저장된 기록을 읽을 수 없습니다. 새 실험 또는 JSON 가져오기를 사용하세요.','Saved data could not be read. Start a new venture or import JSON.'));}
try{if(location.hash.startsWith('#state='))source=validateState(JSON.parse(decodeURIComponent(location.hash.slice(7))));}catch{notify(t('연결된 시작 상태를 확인할 수 없습니다.','The transferred starting state could not be read.'));}
if(location.hash)history.replaceState(null,'',location.pathname+location.search);
if(params.get('source')==='module3'&&source){if(session?.history.length){render();replaceGuard(()=>setup(source));}else setup(source);}
else if(session){activeRole=session.productRole||({'ceo':'CEO','finance':'CFO','growth':'Growth','product':'Product'})[session.experience?.role]||'CEO';enter();}
else if(isDemo){session=createSession(demoState());session.experience={role:'ceo'};save();enter();track('demo_start');}
else setup(source&&params.get('source')==='module3'?source:null);
if(!isDemo&&params.get('mode')==='quick'){try{const q=sessionStorage.getItem('asnm:entry-question');if(q){content.prepend(el('p',{class:'p-notice',text:t('나의 질문: ','Your question: ')+q.slice(0,600)}));sessionStorage.removeItem('asnm:entry-question');}}catch{}}

